"""International Tax Module — Omega Super AI v10

Comprehensive tax knowledge base covering 190+ countries.
Educational purposes only — does not replace professional tax advice.

This module provides:
  • Tax authority directory for 100+ countries
  • Detailed tax system profiles (income tax, corporate tax, VAT/GST, etc.)
  • Progressive income tax calculators for 20 major countries
  • Digital nomad tax guides
  • Double taxation treaty information
  • Expatriate tax basics
  • Tax compliance requirement checkers

Usage::
    from omega.tax_module import InternationalTax
    tax = InternationalTax()
    tax.get_tax_authority("United States")
    tax.estimate_income_tax("United States", 85000, filing_status="single")
"""

from __future__ import annotations

from typing import Any, Final

# ---------------------------------------------------------------------------
# Module constants
# ---------------------------------------------------------------------------

DISCLAIMER: Final[str] = (
    "⚠️ DISCLAIMER: This information is for educational purposes only and "
    "does NOT constitute professional tax, legal, or financial advice. "
    "Tax laws change frequently and vary by jurisdiction. Always consult "
    "a qualified tax professional or the relevant tax authority before "
    "making decisions that affect your tax obligations."
)

LAST_UPDATED: Final[str] = "2025-01-15"


class InternationalTax:
    """Comprehensive international tax knowledge base and advisory module.

    Provides access to tax authority information, tax system profiles,
    income tax calculators, digital nomad guides, double taxation treaty
    data, expatriate tax basics, and compliance checkers for 190+
    jurisdictions.

    All methods include an educational disclaimer and are intended as
    a starting point for tax research, not as a substitute for
    professional advice.
    """

    # ========================================================================
    # 1. TAX AUTHORITY DIRECTORY
    # ========================================================================

    _TAX_AUTHORITIES: dict[str, dict[str, str]] = {
        # --- G20 Countries ---
        "united states": {
            "country": "United States",
            "authority_name": "Internal Revenue Service (IRS)",
            "website": "https://www.irs.gov",
            "e_filing_url": "https://www.irs.gov/filing/free-file-do-your-federal-taxes-for-free",
            "contact_phone": "+1-800-829-1040",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "united kingdom": {
            "country": "United Kingdom",
            "authority_name": "HM Revenue & Customs (HMRC)",
            "website": "https://www.gov.uk/government/organisations/hm-revenue-customs",
            "e_filing_url": "https://www.gov.uk/log-in-file-self-assessment-tax-return",
            "contact_phone": "+44-135-535-9022",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "canada": {
            "country": "Canada",
            "authority_name": "Canada Revenue Agency (CRA)",
            "website": "https://www.canada.ca/en/revenue-agency.html",
            "e_filing_url": "https://www.canada.ca/en/revenue-agency/services/e-services/digital-services-individuals/netfile-overview.html",
            "contact_phone": "+1-800-959-8281",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "australia": {
            "country": "Australia",
            "authority_name": "Australian Taxation Office (ATO)",
            "website": "https://www.ato.gov.au",
            "e_filing_url": "https://www.ato.gov.au/individuals/lodging-your-tax-return/",
            "contact_phone": "+61-2-6216-1111",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "germany": {
            "country": "Germany",
            "authority_name": "Federal Central Tax Office (BZSt)",
            "website": "https://www.bzst.de",
            "e_filing_url": "https://www.elster.de",
            "contact_phone": "+49-208-999-5760",
            "contact_email": "service@bzst.bund.de",
            "last_updated": LAST_UPDATED,
        },
        "france": {
            "country": "France",
            "authority_name": "Direction Générale des Finances Publiques (DGFiP)",
            "website": "https://www.impots.gouv.fr",
            "e_filing_url": "https://www.impots.gouv.fr/portal/dataset/recueil-des-actes-administratifs",
            "contact_phone": "+33-809-401-401",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "italy": {
            "country": "Italy",
            "authority_name": "Agenzia delle Entrate",
            "website": "https://www.agenziaentrate.gov.it",
            "e_filing_url": "https://telematici.agenziaentrate.gov.it/Main/index.jsp",
            "contact_phone": "+39-06-966-68907",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "spain": {
            "country": "Spain",
            "authority_name": "Agencia Tributaria (AEAT)",
            "website": "https://www.agenciatributaria.gob.es",
            "e_filing_url": "https://www.agenciatributaria.gob.es/AEAT.sede/en_GB/procedimientoini/ZP02.shtml",
            "contact_phone": "+34-901-335-533",
            "contact_email": "atencionalusuario@correo.aeat.es",
            "last_updated": LAST_UPDATED,
        },
        "netherlands": {
            "country": "Netherlands",
            "authority_name": "Belastingdienst (Tax and Customs Administration)",
            "website": "https://www.belastingdienst.nl",
            "e_filing_url": "https://www.belastingdienst.nl/wps/wcm/connect/en/content/hoofdwebsite-t-aanmelden-mijn-toeslagen",
            "contact_phone": "+31-555-385-001",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "belgium": {
            "country": "Belgium",
            "authority_name": "FPS Finance (SPF Finances / FOD Financiën)",
            "website": "https://finance.belgium.be",
            "e_filing_url": "https://tax-on-web.be",
            "contact_phone": "+32-2-572-5757",
            "contact_email": "info@minfin.fed.be",
            "last_updated": LAST_UPDATED,
        },
        "switzerland": {
            "country": "Switzerland",
            "authority_name": "Federal Tax Administration (FTA / ESTV)",
            "website": "https://www.estv.admin.ch",
            "e_filing_url": "https://www.estv.admin.ch/estv/en/home/direct-federal-tax/tax-return.html",
            "contact_phone": "+41-58-465-16-11",
            "contact_email": "info@estv.admin.ch",
            "last_updated": LAST_UPDATED,
        },
        "austria": {
            "country": "Austria",
            "authority_name": "Bundesministerium für Finanzen (BMF)",
            "website": "https://www.bmf.gv.at",
            "e_filing_url": "https://finanzonline.bmf.gv.at",
            "contact_phone": "+43-50-233-780",
            "contact_email": "service@bmf.gv.at",
            "last_updated": LAST_UPDATED,
        },
        "sweden": {
            "country": "Sweden",
            "authority_name": "Skatteverket (Swedish Tax Agency)",
            "website": "https://www.skatteverket.se",
            "e_filing_url": "https://www.skatteverket.se/servicelankar/otherlanguages/inenglish/individualsandemployees/declaringtaxesforprivateindividuals",
            "contact_phone": "+46-771-567-567",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "norway": {
            "country": "Norway",
            "authority_name": "Skatteetaten (Norwegian Tax Administration)",
            "website": "https://www.skatteetaten.no",
            "e_filing_url": "https://www.skatteetaten.no/en/person/taxes/do-your-tax-return/",
            "contact_phone": "+47-22-07-70-00",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "denmark": {
            "country": "Denmark",
            "authority_name": "Skattestyrelsen (Danish Tax Agency)",
            "website": "https://skat.dk",
            "e_filing_url": "https://www.tastselv.skat.dk",
            "contact_phone": "+45-72-22-18-18",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "finland": {
            "country": "Finland",
            "authority_name": "Verohallinto (Finnish Tax Administration)",
            "website": "https://www.vero.fi",
            "e_filing_url": "https://www.vero.fi/en/individuals-and-families/returning-online",
            "contact_phone": "+358-29-497-050",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "ireland": {
            "country": "Ireland",
            "authority_name": "Revenue Commissioners",
            "website": "https://www.revenue.ie",
            "e_filing_url": "https://www.ros.ie/osc-web/",
            "contact_phone": "+353-1-738-3663",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "poland": {
            "country": "Poland",
            "authority_name": "Ministry of Finance / Krajowa Administracja Skarbowa",
            "website": "https://www.gov.pl/web/finanse",
            "e_filing_url": "https://www.podatki.gov.pl",
            "contact_phone": "+48-22-694-55-55",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "portugal": {
            "country": "Portugal",
            "authority_name": "Autoridade Tributária e Aduaneira (AT)",
            "website": "https://www.portaldasfinancas.gov.pt",
            "e_filing_url": "https://www.portaldasfinancas.gov.pt/main.jsp",
            "contact_phone": "+351-217-206-707",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "greece": {
            "country": "Greece",
            "authority_name": "Independent Authority for Public Revenue (AADE)",
            "website": "https://www.aade.gr",
            "e_filing_url": "https://www.aade.gr/online-services",
            "contact_phone": "+30-213-16-28-000",
            "contact_email": "info@aade.gr",
            "last_updated": LAST_UPDATED,
        },
        "czech republic": {
            "country": "Czech Republic",
            "authority_name": "Financial Administration (Finanční správa)",
            "website": "https://www.financnisprava.cz",
            "e_filing_url": "https://adisepo.mfcr.cz/adistc/AdisIdCustRegBasic",
            "contact_phone": "+420-225-342-111",
            "contact_email": "podatelna@mfcr.cz",
            "last_updated": LAST_UPDATED,
        },
        "hungary": {
            "country": "Hungary",
            "authority_name": "National Tax and Customs Administration (NAV)",
            "website": "https://www.nav.gov.hu",
            "e_filing_url": "https://eszja.nav.gov.hu",
            "contact_phone": "+36-1-459-5000",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "romania": {
            "country": "Romania",
            "authority_name": "National Agency for Fiscal Administration (ANAF)",
            "website": "https://www.anaf.ro",
            "e_filing_url": "https://www.anaf.ro/anaf/internet/ANAF/servicii_online/declaratii_electronice",
            "contact_phone": "+40-21-306-5590",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "bulgaria": {
            "country": "Bulgaria",
            "authority_name": "National Revenue Agency (NAP)",
            "website": "https://nap.bg",
            "e_filing_url": "https://dec2021.nap.bg",
            "contact_phone": "+359-2-985-921-10",
            "contact_email": "info@nap.bg",
            "last_updated": LAST_UPDATED,
        },
        "croatia": {
            "country": "Croatia",
            "authority_name": "Tax Administration (Porezna uprava)",
            "website": "https://www.porezna-uprava.hr",
            "e_filing_url": "https://lana.porezna-uprava.hr",
            "contact_phone": "+385-1-480-9000",
            "contact_email": "porezna.uprava@porezna-uprava.hr",
            "last_updated": LAST_UPDATED,
        },
        "slovakia": {
            "country": "Slovakia",
            "authority_name": "Financial Administration (Finančná správa)",
            "website": "https://www.financnasprava.sk",
            "e_filing_url": "https://www.financnasprava.sk/-/danove-priznanie-za-rok-2025",
            "contact_phone": "+421-2-581-711-11",
            "contact_email": "podatelna@srsk.sk",
            "last_updated": LAST_UPDATED,
        },
        "slovenia": {
            "country": "Slovenia",
            "authority_name": "Financial Administration (Finančna uprava)",
            "website": "https://www.gov.si/drzavni-organi/organi-v-sestavi/finančna-uprava/",
            "e_filing_url": "https://edavki.durs.si",
            "contact_phone": "+386-1-369-6100",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "lithuania": {
            "country": "Lithuania",
            "authority_name": "State Tax Inspectorate (VMI)",
            "website": "https://www.vmi.lt",
            "e_filing_url": "https://deklaravimas.vmi.lt",
            "contact_phone": "+370-5-268-7185",
            "contact_email": "vmi@vmi.lt",
            "last_updated": LAST_UPDATED,
        },
        "latvia": {
            "country": "Latvia",
            "authority_name": "State Revenue Service (VID)",
            "website": "https://www.vid.gov.lv",
            "e_filing_url": "https://www.vid.gov.lv/lv/e-parvaldiba",
            "contact_phone": "+371-671-200-00",
            "contact_email": "info@vid.gov.lv",
            "last_updated": LAST_UPDATED,
        },
        "estonia": {
            "country": "Estonia",
            "authority_name": "Tax and Customs Board (MTA)",
            "website": "https://www.emta.ee",
            "e_filing_url": "https://www.emta.ee/en/tax-free-allowance-and-tax-return",
            "contact_phone": "+372-880-0707",
            "contact_email": "emta@emta.ee",
            "last_updated": LAST_UPDATED,
        },
        "luxembourg": {
            "country": "Luxembourg",
            "authority_name": "Administration des Contributions Directes (ACD)",
            "website": "https://impotsdirects.public.lu",
            "e_filing_url": "https://impotsdirects.public.lu/en/myguichet.html",
            "contact_phone": "+352-408-001",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "malta": {
            "country": "Malta",
            "authority_name": "Commissioner for Revenue",
            "website": "https://cfr.gov.mt",
            "e_filing_url": "https://cfr.gov.mt/en/eServices/Pages/Online-Services.aspx",
            "contact_phone": "+356-229-666-00",
            "contact_email": "info.inlandrevenue@gov.mt",
            "last_updated": LAST_UPDATED,
        },
        "cyprus": {
            "country": "Cyprus",
            "authority_name": "Tax Department / Inland Revenue",
            "website": "https://www.mof.gov.cy/tax",
            "e_filing_url": "https://www.taxdepartment.gov.cy",
            "contact_phone": "+357-2260-2700",
            "contact_email": "taxinfo@taxdepartment.gov.cy",
            "last_updated": LAST_UPDATED,
        },
        # --- BRICS / Major Asian Economies ---
        "china": {
            "country": "China",
            "authority_name": "State Taxation Administration (STA)",
            "website": "https://www.chinatax.gov.cn",
            "e_filing_url": "https://etax.chinatax.gov.cn",
            "contact_phone": "+86-10-6341-7114",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "india": {
            "country": "India",
            "authority_name": "Central Board of Direct Taxes (CBDT) / Income Tax Department",
            "website": "https://www.incometax.gov.in",
            "e_filing_url": "https://www.incometax.gov.in/iec/foportal/",
            "contact_phone": "+91-1800-103-0025",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "japan": {
            "country": "Japan",
            "authority_name": "National Tax Agency (NTA)",
            "website": "https://www.nta.go.jp",
            "e_filing_url": "https://www.e-tax.nta.go.jp",
            "contact_phone": "+81-3-3581-4161",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "south korea": {
            "country": "South Korea",
            "authority_name": "National Tax Service (NTS)",
            "website": "https://www.nts.go.kr",
            "e_filing_url": "https://www.nts.go.kr/eng/",
            "contact_phone": "+82-1588-0061",
            "contact_email": "webmaster@nts.go.kr",
            "last_updated": LAST_UPDATED,
        },
        "indonesia": {
            "country": "Indonesia",
            "authority_name": "Directorate General of Taxes (DGT)",
            "website": "https://www.pajak.go.id",
            "e_filing_url": "https://djponline.pajak.go.id",
            "contact_phone": "+62-21-525-0209",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "malaysia": {
            "country": "Malaysia",
            "authority_name": "Inland Revenue Board of Malaysia (LHDN / IRB)",
            "website": "https://www.hasil.gov.my",
            "e_filing_url": "https://ez.hasil.gov.my",
            "contact_phone": "+603-8313-8888",
            "contact_email": "yukm@hasil.gov.my",
            "last_updated": LAST_UPDATED,
        },
        "philippines": {
            "country": "Philippines",
            "authority_name": "Bureau of Internal Revenue (BIR)",
            "website": "https://www.bir.gov.ph",
            "e_filing_url": "https://efps.bir.gov.ph",
            "contact_phone": "+63-2-8538-3200",
            "contact_email": "contact_us@bir.gov.ph",
            "last_updated": LAST_UPDATED,
        },
        "thailand": {
            "country": "Thailand",
            "authority_name": "Revenue Department",
            "website": "https://www.rd.go.th",
            "e_filing_url": "https://efiling.rd.go.th/rd-cms/",
            "contact_phone": "+66-2-272-8000",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "vietnam": {
            "country": "Vietnam",
            "authority_name": "General Department of Taxation (GDT)",
            "website": "https://www.gdt.gov.vn",
            "e_filing_url": "https://thuedientu.gdt.gov.vn",
            "contact_phone": "+84-24-3767-6666",
            "contact_email": "tongcuucthue@gdt.gov.vn",
            "last_updated": LAST_UPDATED,
        },
        "singapore": {
            "country": "Singapore",
            "authority_name": "Inland Revenue Authority of Singapore (IRAS)",
            "website": "https://www.iras.gov.sg",
            "e_filing_url": "https://mytax.iras.gov.sg",
            "contact_phone": "+65-6351-3000",
            "contact_email": "iras_contact@iras.gov.sg",
            "last_updated": LAST_UPDATED,
        },
        "bangladesh": {
            "country": "Bangladesh",
            "authority_name": "National Board of Revenue (NBR)",
            "website": "https://nbr.gov.bd",
            "e_filing_url": "https://etaxnbr.gov.bd",
            "contact_phone": "+880-2-911-0354",
            "contact_email": "info@nbr.gov.bd",
            "last_updated": LAST_UPDATED,
        },
        "pakistan": {
            "country": "Pakistan",
            "authority_name": "Federal Board of Revenue (FBR)",
            "website": "https://www.fbr.gov.pk",
            "e_filing_url": "https://iris.fbr.gov.pk",
            "contact_phone": "+92-51-111-772-772",
            "contact_email": "helpdesk@fbr.gov.pk",
            "last_updated": LAST_UPDATED,
        },
        "sri lanka": {
            "country": "Sri Lanka",
            "authority_name": "Inland Revenue Department (IRD)",
            "website": "https://www.ird.gov.lk",
            "e_filing_url": "https://eportal.ird.gov.lk",
            "contact_phone": "+94-11-219-6969",
            "contact_email": "ird@sltnet.lk",
            "last_updated": LAST_UPDATED,
        },
        "nepal": {
            "country": "Nepal",
            "authority_name": "Inland Revenue Department (IRD)",
            "website": "https://ird.gov.np",
            "e_filing_url": "https://ird.gov.np/online-services",
            "contact_phone": "+977-1-447-0170",
            "contact_email": "info@ird.gov.np",
            "last_updated": LAST_UPDATED,
        },
        "myanmar": {
            "country": "Myanmar",
            "authority_name": "Internal Revenue Department (IRD)",
            "website": "https://www.irdmyanmar.gov.mm",
            "e_filing_url": "",
            "contact_phone": "+95-1-370-546",
            "contact_email": "ird@mptmail.net.mm",
            "last_updated": LAST_UPDATED,
        },
        "cambodia": {
            "country": "Cambodia",
            "authority_name": "General Department of Taxation (GDT)",
            "website": "https://www.tax.gov.kh",
            "e_filing_url": "https://www.tax.gov.kh/e-services",
            "contact_phone": "+855-23-886-708",
            "contact_email": "info@tax.gov.kh",
            "last_updated": LAST_UPDATED,
        },
        "laos": {
            "country": "Laos",
            "authority_name": "Tax Department, Ministry of Finance",
            "website": "https://www.mof.gov.la",
            "e_filing_url": "",
            "contact_phone": "+856-21-454-038",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "brunei": {
            "country": "Brunei",
            "authority_name": "Ministry of Finance / Revenue Division",
            "website": "https://www.mof.gov.bn",
            "e_filing_url": "",
            "contact_phone": "+673-238-0538",
            "contact_email": "revenue@mof.gov.bn",
            "last_updated": LAST_UPDATED,
        },
        # --- Middle East ---
        "united arab emirates": {
            "country": "United Arab Emirates",
            "authority_name": "Federal Tax Authority (FTA)",
            "website": "https://www.tax.gov.ae",
            "e_filing_url": "https://eservices.tax.gov.ae",
            "contact_phone": "+971-600-599-994",
            "contact_email": "info@tax.gov.ae",
            "last_updated": LAST_UPDATED,
        },
        "saudi arabia": {
            "country": "Saudi Arabia",
            "authority_name": "Zakat, Tax and Customs Authority (ZATCA)",
            "website": "https://www.zatca.gov.sa",
            "e_filing_url": "https://zatca.gov.sa/ar/eservices/Pages/default.aspx",
            "contact_phone": "+966-11-205-4444",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "israel": {
            "country": "Israel",
            "authority_name": "Israel Tax Authority (ITA / Rasham HaMaas)",
            "website": "https://www.taxes.gov.il",
            "e_filing_url": "https://www.taxes.gov.il/svataonline/html/he/Main/Main.aspx",
            "contact_phone": "+972-1-800-30-02-05",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "turkey": {
            "country": "Turkey",
            "authority_name": "Revenue Administration (Gelir İdaresi Başkanlığı / GIB)",
            "website": "https://www.gib.gov.tr",
            "e_filing_url": "https://intvrg.gib.gov.tr",
            "contact_phone": "+90-444-0-189",
            "contact_email": "bilgiislemdairebaskanligi@gib.gov.tr",
            "last_updated": LAST_UPDATED,
        },
        "egypt": {
            "country": "Egypt",
            "authority_name": "Egyptian Tax Authority (ETA)",
            "website": "https://eta.gov.eg",
            "e_filing_url": "https://www.eta.gov.eg/ar/electronicServices/Pages/default.aspx",
            "contact_phone": "+20-2-279-555-55",
            "contact_email": "info@eta.gov.eg",
            "last_updated": LAST_UPDATED,
        },
        "kuwait": {
            "country": "Kuwait",
            "authority_name": "Ministry of Finance",
            "website": "https://www.mof.gov.kw",
            "e_filing_url": "",
            "contact_phone": "+965-1-805-008",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "qatar": {
            "country": "Qatar",
            "authority_name": "General Tax Authority (GTA)",
            "website": "https://gta.gov.qa",
            "e_filing_url": "https://gta.gov.qa/en/eta",
            "contact_phone": "+974-4441-1555",
            "contact_email": "info@gta.gov.qa",
            "last_updated": LAST_UPDATED,
        },
        "bahrain": {
            "country": "Bahrain",
            "authority_name": "Ministry of Finance & National Economy",
            "website": "https://www.mofne.gov.bh",
            "e_filing_url": "https://www.mofne.gov.bh/Tax/VAT?culture=en-us",
            "contact_phone": "+973-17-557-700",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "oman": {
            "country": "Oman",
            "authority_name": "Secretariat General for Taxation (SGT)",
            "website": "https://www.taxoman.gov.om",
            "e_filing_url": "https://tms.taxoman.gov.om",
            "contact_phone": "+968-2477-7500",
            "contact_email": "info@taxoman.gov.om",
            "last_updated": LAST_UPDATED,
        },
        "jordan": {
            "country": "Jordan",
            "authority_name": "Income and Sales Tax Department (ISTD)",
            "website": "https://www.istd.gov.jo",
            "e_filing_url": "https://e-services.istd.gov.jo",
            "contact_phone": "+962-6-460-7010",
            "contact_email": "info@istd.gov.jo",
            "last_updated": LAST_UPDATED,
        },
        "lebanon": {
            "country": "Lebanon",
            "authority_name": "Ministry of Finance",
            "website": "https://www.finance.gov.lb",
            "e_filing_url": "",
            "contact_phone": "+961-1-647-000",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        # --- African Union Members ---
        "south africa": {
            "country": "South Africa",
            "authority_name": "South African Revenue Service (SARS)",
            "website": "https://www.sars.gov.za",
            "e_filing_url": "https://www.sarsefiling.co.za",
            "contact_phone": "+27-12-422-4000",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "nigeria": {
            "country": "Nigeria",
            "authority_name": "Federal Inland Revenue Service (FIRS)",
            "website": "https://www.firs.gov.ng",
            "e_filing_url": "https://efiling.firs.gov.ng",
            "contact_phone": "+234-9-462-18000",
            "contact_email": "info@firs.gov.ng",
            "last_updated": LAST_UPDATED,
        },
        "kenya": {
            "country": "Kenya",
            "authority_name": "Kenya Revenue Authority (KRA)",
            "website": "https://www.kra.go.ke",
            "e_filing_url": "https://itax.kra.go.ke",
            "contact_phone": "+254-20-281-0000",
            "contact_email": "callcentre@kra.go.ke",
            "last_updated": LAST_UPDATED,
        },
        "ghana": {
            "country": "Ghana",
            "authority_name": "Ghana Revenue Authority (GRA)",
            "website": "https://www.gra.gov.gh",
            "e_filing_url": "https://taxpayersportal.com",
            "contact_phone": "+233-302-904-435",
            "contact_email": "info@gra.gov.gh",
            "last_updated": LAST_UPDATED,
        },
        "ethiopia": {
            "country": "Ethiopia",
            "authority_name": "Ethiopian Revenue and Customs Authority (ERCA)",
            "website": "https://www.erca.gov.et",
            "e_filing_url": "",
            "contact_phone": "+251-11-662-9196",
            "contact_email": "info@erca.gov.et",
            "last_updated": LAST_UPDATED,
        },
        "morocco": {
            "country": "Morocco",
            "authority_name": "Direction Générale des Impôts (DGI)",
            "website": "https://www.portnet.ma",
            "e_filing_url": "https://www.tax.gov.ma/wps/portal/DGI",
            "contact_phone": "+212-537-577-000",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "algeria": {
            "country": "Algeria",
            "authority_name": "Direction Générale des Impôts",
            "website": "https://www.mfdgi.gov.dz",
            "e_filing_url": "",
            "contact_phone": "+213-21-63-87-87",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "tunisia": {
            "country": "Tunisia",
            "authority_name": "Direction Générale des Impôts",
            "website": "https://www.impots.finances.tn",
            "e_filing_url": "https://www.impots.finances.tn/index.php/fr/",
            "contact_phone": "+216-71-33-11-00",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "zimbabwe": {
            "country": "Zimbabwe",
            "authority_name": "Zimbabwe Revenue Authority (ZIMRA)",
            "website": "https://www.zimra.co.zw",
            "e_filing_url": "https://www.zimra.co.zw/tax-services/e-services",
            "contact_phone": "+263-4-759-341",
            "contact_email": "prs@zimra.co.zw",
            "last_updated": LAST_UPDATED,
        },
        "zambia": {
            "country": "Zambia",
            "authority_name": "Zambia Revenue Authority (ZRA)",
            "website": "https://www.zra.org.zm",
            "e_filing_url": "https://www.zra.org.zm/taxpayer-portal",
            "contact_phone": "+260-211-840-000",
            "contact_email": "info@zra.org.zm",
            "last_updated": LAST_UPDATED,
        },
        "botswana": {
            "country": "Botswana",
            "authority_name": "Botswana Unified Revenue Service (BURS)",
            "website": "https://www.burs.org.bw",
            "e_filing_url": "https://efiling.burs.org.bw",
            "contact_phone": "+267-363-2500",
            "contact_email": "info@burs.org.bw",
            "last_updated": LAST_UPDATED,
        },
        "namibia": {
            "country": "Namibia",
            "authority_name": "Inland Revenue Department",
            "website": "https://www.mof.gov.na/ird",
            "e_filing_url": "https://efiling.mof.gov.na",
            "contact_phone": "+264-61-209-2644",
            "contact_email": "info@mof.gov.na",
            "last_updated": LAST_UPDATED,
        },
        "tanzania": {
            "country": "Tanzania",
            "authority_name": "Tanzania Revenue Authority (TRA)",
            "website": "https://www.tra.go.tz",
            "e_filing_url": "https://etax.tra.go.tz",
            "contact_phone": "+255-22-211-3213",
            "contact_email": "commissioner.general@tra.go.tz",
            "last_updated": LAST_UPDATED,
        },
        "uganda": {
            "country": "Uganda",
            "authority_name": "Uganda Revenue Authority (URA)",
            "website": "https://www.ura.go.ug",
            "e_filing_url": "https://ura.go.ug/en/efiling/",
            "contact_phone": "+256-417-701-000",
            "contact_email": "info@ura.go.ug",
            "last_updated": LAST_UPDATED,
        },
        "rwanda": {
            "country": "Rwanda",
            "authority_name": "Rwanda Revenue Authority (RRA)",
            "website": "https://www.rra.gov.rw",
            "e_filing_url": "https://etax.rra.gov.rw",
            "contact_phone": "+250-252-577-111",
            "contact_email": "info@rra.gov.rw",
            "last_updated": LAST_UPDATED,
        },
        "ug": {  # alias
            "country": "Uganda",
            "authority_name": "Uganda Revenue Authority (URA)",
            "website": "https://www.ura.go.ug",
            "e_filing_url": "https://ura.go.ug/en/efiling/",
            "contact_phone": "+256-417-701-000",
            "contact_email": "info@ura.go.ug",
            "last_updated": LAST_UPDATED,
        },
        "cameroon": {
            "country": "Cameroon",
            "authority_name": "Direction Générale des Impôts",
            "website": "https://www.impots.cm",
            "e_filing_url": "",
            "contact_phone": "+237-222-23-40-66",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "ivory coast": {
            "country": "Ivory Coast",
            "authority_name": "Direction Générale des Impôts (DGI)",
            "website": "https://www.dgi.gouv.ci",
            "e_filing_url": "",
            "contact_phone": "+225-20-25-11-11",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "senegal": {
            "country": "Senegal",
            "authority_name": "Direction Générale des Impôts et des Domaines (DGID)",
            "website": "https://www.dgid.gouv.sn",
            "e_filing_url": "https://www.dgid.gouv.sn/accueil",
            "contact_phone": "+221-33-889-50-00",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "mauritius": {
            "country": "Mauritius",
            "authority_name": "Mauritius Revenue Authority (MRA)",
            "website": "https://www.mra.mu",
            "e_filing_url": "https://eservices.mra.mu",
            "contact_phone": "+230-207-2500",
            "contact_email": "mra@mra.mu",
            "last_updated": LAST_UPDATED,
        },
        "seychelles": {
            "country": "Seychelles",
            "authority_name": "Seychelles Revenue Commission (SRC)",
            "website": "https://www.src.gov.sc",
            "e_filing_url": "https://etax.gov.sc",
            "contact_phone": "+248-4-293-737",
            "contact_email": "info@src.gov.sc",
            "last_updated": LAST_UPDATED,
        },
        # --- Latin America ---
        "brazil": {
            "country": "Brazil",
            "authority_name": "Receita Federal do Brasil (RFB)",
            "website": "https://www.gov.br/receitafederal",
            "e_filing_url": "https://www.gov.br/receitafederal/pt-br/assuntos/orientacao-tributaria/declaracoes-e-demonstrativos",
            "contact_phone": "+55-61-3412-2000",
            "contact_email": "faleconosco@rfb.gov.br",
            "last_updated": LAST_UPDATED,
        },
        "mexico": {
            "country": "Mexico",
            "authority_name": "Servicio de Administración Tributaria (SAT)",
            "website": "https://www.sat.gob.mx",
            "e_filing_url": "https://portalsat.plataforma.sat.gob.mx",
            "contact_phone": "+52-55-6272-2728",
            "contact_email": "asistencia_fiscal@sat.gob.mx",
            "last_updated": LAST_UPDATED,
        },
        "argentina": {
            "country": "Argentina",
            "authority_name": "Administración Federal de Ingresos Públicos (AFIP)",
            "website": "https://www.afip.gob.ar",
            "e_filing_url": "https://serviciosweb.afip.gob.ar/genericos/imprentas/constancia.aspx",
            "contact_phone": "+54-11-4347-2000",
            "contact_email": "mesadeayuda@afip.gob.ar",
            "last_updated": LAST_UPDATED,
        },
        "chile": {
            "country": "Chile",
            "authority_name": "Servicio de Impuestos Internos (SII)",
            "website": "https://www.sii.cl",
            "e_filing_url": "https://www.sii.cl/servicios_online/1038-1038.html",
            "contact_phone": "+56-2-3252-3000",
            "contact_email": "callcenter@sii.cl",
            "last_updated": LAST_UPDATED,
        },
        "colombia": {
            "country": "Colombia",
            "authority_name": "Unidad Administrativa Especial de Dirección de Impuestos y Aduanas Nacionales (DIAN)",
            "website": "https://www.dian.gov.co",
            "e_filing_url": "https://muisca.dian.gov.co/WebArquitectura/DefLoginOld.faces",
            "contact_phone": "+57-601-355-1111",
            "contact_email": "contactenos@dian.gov.co",
            "last_updated": LAST_UPDATED,
        },
        "peru": {
            "country": "Peru",
            "authority_name": "Superintendencia Nacional de Aduanas y de Administración Tributaria (SUNAT)",
            "website": "https://www.sunat.gob.pe",
            "e_filing_url": "https://www.sunat.gob.pe/sol.html",
            "contact_phone": "+51-1-315-0730",
            "contact_email": "asistencia@sunat.gob.pe",
            "last_updated": LAST_UPDATED,
        },
        "costa rica": {
            "country": "Costa Rica",
            "authority_name": "Ministerio de Hacienda / Dirección General de Tributación",
            "website": "https://www.hacienda.go.cr",
            "e_filing_url": "https://atv.hacienda.go.cr/ATV/Login.aspx",
            "contact_phone": "+506-2539-3700",
            "contact_email": "contacto@hacienda.go.cr",
            "last_updated": LAST_UPDATED,
        },
        "panama": {
            "country": "Panama",
            "authority_name": "Dirección General de Ingresos (DGI)",
            "website": "https://www.dgi.gob.pa",
            "e_filing_url": "https://etax.mef.gob.pa",
            "contact_phone": "+507-507-6000",
            "contact_email": "atencionciudadano@dgi.gob.pa",
            "last_updated": LAST_UPDATED,
        },
        "venezuela": {
            "country": "Venezuela",
            "authority_name": "Servicio Nacional Integrado de Administración Aduanera y Tributaria (SENIAT)",
            "website": "https://www.seniat.gob.ve",
            "e_filing_url": "",
            "contact_phone": "+58-212-905-7000",
            "contact_email": "",
            "last_updated": LAST_UPDATED,
        },
        "uruguay": {
            "country": "Uruguay",
            "authority_name": "Dirección General Impositiva (DGI)",
            "website": "https://www.gub.uy/direccion-general-impositiva",
            "e_filing_url": "https://www.gub.uy/direccion-general-impositiva/tramites-y-servicios",
            "contact_phone": "+598-2902-9243",
            "contact_email": "info@dgi.gub.uy",
            "last_updated": LAST_UPDATED,
        },
        "paraguay": {
            "country": "Paraguay",
            "authority_name": "Subsecretaría de Estado de Tributación (SET)",
            "website": "https://www.set.gov.py",
            "e_filing_url": "https://www.set.gov.py/portal/index.php",
            "contact_phone": "+595-21-417-5000",
            "contact_email": "info@set.gov.py",
            "last_updated": LAST_UPDATED,
        },
        "ecuador": {
            "country": "Ecuador",
            "authority_name": "Servicio de Rentas Internas (SRI)",
            "website": "https://www.sri.gob.ec",
            "e_filing_url": "https://srienlinea.sri.gob.ec",
            "contact_phone": "+593-2-3978-200",
            "contact_email": "callcenter@sri.gob.ec",
            "last_updated": LAST_UPDATED,
        },
        "bolivia": {
            "country": "Bolivia",
            "authority_name": "Servicio de Impuestos Nacionales (SIN)",
            "website": "https://www.impuestos.gob.bo",
            "e_filing_url": "https://pi.impuestos.gob.bo",
            "contact_phone": "+591-2-200-2020",
            "contact_email": "infosenave@impuestos.gob.bo",
            "last_updated": LAST_UPDATED,
        },
        "guatemala": {
            "country": "Guatemala",
            "authority_name": "Superintendencia de Administración Tributaria (SAT Guatemala)",
            "website": "https://www.sat.gob.gt",
            "e_filing_url": "https://www.sat.gob.gt/portal/",
            "contact_phone": "+502-2327-4040",
            "contact_email": "sat@sucursalvirtual.sat.gob.gt",
            "last_updated": LAST_UPDATED,
        },
        # --- Offshore & Caribbean ---
        "cayman islands": {
            "country": "Cayman Islands",
            "authority_name": "Department of Financial Services / Tax Information Authority",
            "website": "https://www.dfs.gov.ky",
            "e_filing_url": "",
            "contact_phone": "+1-345-949-7080",
            "contact_email": "dfs@gov.ky",
            "last_updated": LAST_UPDATED,
        },
        "bahamas": {
            "country": "Bahamas",
            "authority_name": "Ministry of Finance / Department of Inland Revenue",
            "website": "https://www.bahamas.gov.bs",
            "e_filing_url": "",
            "contact_phone": "+1-242-702-5080",
            "contact_email": "finance@bahamas.gov.bs",
            "last_updated": LAST_UPDATED,
        },
        "barbados": {
            "country": "Barbados",
            "authority_name": "Barbados Revenue Authority (BRA)",
            "website": "https://www.bra.gov.bb",
            "e_filing_url": "https:// bra.gov.bb/e-services",
            "contact_phone": "+1-246-429-4711",
            "contact_email": "info@bra.gov.bb",
            "last_updated": LAST_UPDATED,
        },
        "jamaica": {
            "country": "Jamaica",
            "authority_name": "Tax Administration Jamaica (TAJ)",
            "website": "https://www.jamaicatax.gov.jm",
            "e_filing_url": "https://www.jamaicatax.gov.jm/e-services",
            "contact_phone": "+1-876-968-8000",
            "contact_email": "tajinfo@taj.gov.jm",
            "last_updated": LAST_UPDATED,
        },
        "trinidad and tobago": {
            "country": "Trinidad and Tobago",
            "authority_name": "Inland Revenue Division (IRD)",
            "website": "https://www.finance.gov.tt/ird",
            "e_filing_url": "https://ird.gov.tt/online-services/",
            "contact_phone": "+1-868-627-1551",
            "contact_email": "ird@ird.gov.tt",
            "last_updated": LAST_UPDATED,
        },
        "bermuda": {
            "country": "Bermuda",
            "authority_name": "Office of the Tax Commissioner",
            "website": "https://www.gov.bm",
            "e_filing_url": "",
            "contact_phone": "+1-441-297-7714",
            "contact_email": "taxcomm@gov.bm",
            "last_updated": LAST_UPDATED,
        },
        "british virgin islands": {
            "country": "British Virgin Islands",
            "authority_name": "International Tax Authority (ITA)",
            "website": "https://www.bviita.org",
            "e_filing_url": "https://www.bviita.org",
            "contact_phone": "+1-284-468-3701",
            "contact_email": "info@bviita.vg",
            "last_updated": LAST_UPDATED,
        },
    }