"""Omega AI v3 — Export Format Engine
Multi-format export: Markdown, CSV, JSON, TXT.
"""
from __future__ import annotations

import csv
import json
import os
from datetime import datetime
from pathlib import Path
from typing import Any


class ExportEngine:
    """Export conversations and data to multiple formats."""

    _EXPORT_DIR = Path.home() / "Luqi-AI" / "exports"

    def __init__(self) -> None:
        self._EXPORT_DIR.mkdir(parents=True, exist_ok=True)

    def auto_export(self, query: str, response_data: dict, fmt: str = "md", filename: str = "") -> str:
        """Route to the correct exporter."""
        fmt = fmt.lower().lstrip(".")
        if fmt in ("md", "markdown"):
            return self.export_markdown(query, response_data.get("response", str(response_data)),
                                        response_data.get("module", ""), response_data.get("sources"), filename)
        elif fmt == "csv":
            return self.export_csv(response_data, filename)
        elif fmt == "json":
            return self.export_json(response_data, filename)
        elif fmt in ("txt", "text"):
            return self.export_txt(query, response_data.get("response", str(response_data)),
                                   response_data.get("module", ""), filename)
        else:
            return f"[Export] Unknown format: {fmt}. Use: md, csv, json, txt"

    def export_markdown(self, query: str, response: str, module: str = "",
                        sources: list | None = None, filename: str = "") -> str:
        """Export to Markdown with frontmatter."""
        fn = self._safe_filename(filename or f"luqi_{module}_{datetime.now():%Y%m%d_%H%M%S}", "md")
        lines = [
            "---",
            f"title: \"Luqi-AI Export\"",
            f"date: {datetime.now().isoformat()}",
            f"module: {module}",
            "---",
            "",
            f"## Query",
            f"{query}",
            "",
            "## Response",
            f"{response}",
        ]
        if sources:
            lines.extend(["", "## Sources"])
            for s in sources:
                lines.append(f"- {s.get('title', 'Unknown')}: {s.get('source', 'N/A')}")
        lines.extend(["", f"---\n*Generated by Luqi-AI v3.2*"])
        Path(fn).write_text("\n".join(lines), encoding="utf-8")
        return fn

    def export_csv(self, data: dict, filename: str = "") -> str:
        """Flatten dict to CSV."""
        fn = self._safe_filename(filename or f"luqi_data_{datetime.now():%Y%m%d_%H%M%S}", "csv")
        with open(fn, "w", newline="", encoding="utf-8") as fh:
            writer = csv.writer(fh)
            writer.writerow(["key", "value"])
            for key, val in data.items():
                if isinstance(val, (dict, list)):
                    val = json.dumps(val)
                writer.writerow([key, val])
        return fn

    def export_json(self, data: dict, filename: str = "") -> str:
        """Pretty JSON with metadata envelope."""
        fn = self._safe_filename(filename or f"luqi_data_{datetime.now():%Y%m%d_%H%M%S}", "json")
        envelope = {
            "_export_meta": {"timestamp": datetime.now().isoformat(), "version": "3.2.0"},
            **data
        }
        Path(fn).write_text(json.dumps(envelope, indent=2, ensure_ascii=False), encoding="utf-8")
        return fn

    def export_txt(self, query: str, response: str, module: str = "", filename: str = "") -> str:
        """Plain text export."""
        fn = self._safe_filename(filename or f"luqi_{module}_{datetime.now():%Y%m%d_%H%M%S}", "txt")
        text = f"Query: {query}\n\nResponse:\n{response}\n\n---\nLuqi-AI v3.2 | {datetime.now().isoformat()}"
        Path(fn).write_text(text, encoding="utf-8")
        return fn

    def _safe_filename(self, base: str, ext: str) -> str:
        safe = "".join(c if c.isalnum() or c in "._-" else "_" for c in base)
        if not safe.endswith(f".{ext}"):
            safe += f".{ext}"
        return str(self._EXPORT_DIR / safe)