    # ========================================================================
    # COURSE 4: ETHICAL HACKING & PENETRATION TESTING
    # ========================================================================
    mod4 = SecurityModule(
        id="ethical_001",
        course_id="ethical_hacking",
        title="Ethical Hacking & Penetration Testing",
        description="Master the art of ethical hacking with hands-on penetration testing methodologies, from reconnaissance to reporting.",
        category=CourseCategory.OFFENSIVE,
        difficulty=DifficultyLevel.ADVANCED,
        duration_hours=20.0,
        prerequisites=["Network Security Fundamentals", "Basic Linux command line"],
        order=4,
        lessons=[
            SecurityLesson(
                id="eth_l1", module_id="ethical_001", title="Penetration Testing Methodology",
                content="Structured approach to penetration testing following PTES (Penetration Testing Execution Standard) and OWASP Testing Guide. Covers pre-engagement interactions, intelligence gathering, threat modeling, vulnerability analysis, exploitation, post-exploitation, and reporting phases.",
                lesson_type=LessonType.TEXT, duration_min=60, order=1,
            ),
            SecurityLesson(
                id="eth_l2", module_id="ethical_001", title="Reconnaissance & OSINT",
                content="Passive and active reconnaissance techniques. Open Source Intelligence (OSINT) gathering using Maltego, theHarvester, Shodan, Censys, and custom tools. DNS enumeration, subdomain discovery, email harvesting, and social media analysis.",
                lesson_type=LessonType.INTERACTIVE, duration_min=55, order=2,
            ),
            SecurityLesson(
                id="eth_l3", module_id="ethical_001", title="Scanning & Enumeration",
                content="Network and service scanning with Nmap, Masscan, and Unicornscan. Service enumeration, banner grabbing, and version detection. SMB, SNMP, LDAP, and DNS enumeration techniques.",
                lesson_type=LessonType.LAB, duration_min=50, order=3,
            ),
            SecurityLesson(
                id="eth_l4", module_id="ethical_001", title="Vulnerability Analysis",
                content="Identifying and validating vulnerabilities using Nessus, OpenVAS, and manual techniques. False positive elimination, vulnerability scoring with CVSS 3.1, and prioritization frameworks.",
                lesson_type=LessonType.INTERACTIVE, duration_min=45, order=4,
            ),
            SecurityLesson(
                id="eth_l5", module_id="ethical_001", title="Exploitation Frameworks",
                content="Metasploit Framework mastery: module selection, payload generation, exploit development, and post-exploitation modules. Empire, Cobalt Strike basics, and custom exploit development with Python.",
                lesson_type=LessonType.LAB, duration_min=70, order=5,
            ),
            SecurityLesson(
                id="eth_l6", module_id="ethical_001", title="Post-Exploitation & Privilege Escalation",
                content="Linux and Windows privilege escalation techniques: kernel exploits, misconfigured permissions, SUID binaries, scheduled tasks, service misconfigurations. Credential harvesting, lateral movement, and persistence mechanisms.",
                lesson_type=LessonType.LAB, duration_min=65, order=6,
            ),
            SecurityLesson(
                id="eth_l7", module_id="ethical_001", title="Web Application Penetration Testing",
                content="Advanced web application testing: authentication bypass, session management flaws, business logic vulnerabilities, API testing, and modern framework-specific issues.",
                lesson_type=LessonType.INTERACTIVE, duration_min=55, order=7,
            ),
            SecurityLesson(
                id="eth_l8", module_id="ethical_001", title="Report Writing & Deliverables",
                content="Professional penetration test reporting: executive summaries, technical findings, risk ratings, remediation recommendations, and evidence collection. CVSS scoring and risk matrix development.",
                lesson_type=LessonType.TEXT, duration_min=40, order=8,
            ),
        ],
        labs=[
            SecurityLab(
                id="eth_lab1", module_id="ethical_001",
                title="Full Network Penetration Test",
                description="Conduct a complete network penetration test from reconnaissance to reporting against a simulated enterprise network.",
                environment="Kali Linux, Metasploitable3, Windows Server 2022, Ubuntu 22.04 targets.",
                tasks=[
                    "Perform OSINT reconnaissance on target organization",
                    "Conduct network scanning and service enumeration",
                    "Identify and exploit vulnerable services",
                    "Escalate privileges on compromised systems",
                    "Perform lateral movement to additional targets",
                    "Establish persistence mechanisms",
                    "Document all findings with evidence",
                    "Create executive and technical reports",
                ],
                hints=[
                    "Start with passive reconnaissance before active scanning",
                    "Use searchsploit to find relevant exploits",
                    "Document every command and its output",
                ],
                solution="Full methodology: recon -> scan -> enumerate -> exploit -> escalate -> pivot -> persist -> report",
                duration_min=180, points=300,
            ),
            SecurityLab(
                id="eth_lab2", module_id="ethical_001",
                title="Web Application Penetration Test",
                description="Perform a comprehensive web application security assessment.",
                environment="OWASP WebGoat, DVWA, and custom vulnerable applications.",
                tasks=[
                    "Map application functionality and attack surface",
                    "Test authentication mechanisms for bypasses",
                    "Test session management for fixation and hijacking",
                    "Identify and exploit injection vulnerabilities",
                    "Test for business logic flaws",
                    "Assess client-side controls and DOM vulnerabilities",
                    "Test APIs for security issues",
                    "Document findings with proof-of-concept exploits",
                ],
                hints=[
                    "Use Burp Suite for systematic testing",
                    "Test every input point for injection",
                    "Check client-side code for security comments",
                ],
                solution="Systematic testing of all OWASP categories with detailed documentation",
                duration_min=150, points=250,
            ),
            SecurityLab(
                id="eth_lab3", module_id="ethical_001",
                title="Privilege Escalation Workshop",
                description="Practice Linux and Windows privilege escalation techniques.",
                environment="Vulnerable Linux and Windows VMs with known misconfigurations.",
                tasks=[
                    "Identify SUID binaries and exploit path traversal",
                    "Exploit kernel vulnerabilities for root access",
                    "Abuse sudo misconfigurations",
                    "Exploit Windows token privileges",
                    "Leverage unquoted service paths",
                    "Exploit scheduled tasks and registry permissions",
                ],
                hints=[
                    "Use LinPEAS and WinPEAS for automated enumeration",
                    "Check sudo -l for allowed commands",
                    "Always check kernel version against known exploits",
                ],
                solution="Comprehensive enumeration followed by targeted exploitation of misconfigurations",
                duration_min=120, points=200,
            ),
        ],
        quiz=SecurityQuiz(
            id="eth_q1", module_id="ethical_001", title="Ethical Hacking Assessment",
            passing_score=80, time_limit_minutes=35,
            questions=[
                QuizQuestion("eh1", "What is the first phase of penetration testing?",
                    ["Exploitation", "Reconnaissance", "Reporting", "Scanning"], 1,
                    "Reconnaissance is always the first phase to gather information.", DifficultyLevel.BEGINNER),
                QuizQuestion("eh2", "Which tool is best for automated vulnerability scanning?",
                    ["Nmap", "Nessus", "Metasploit", "Wireshark"], 1,
                    "Nessus is a dedicated vulnerability scanner.", DifficultyLevel.BEGINNER),
                QuizQuestion("eh3", "What does SUID stand for?",
                    ["System User ID", "Set User ID", "Secure User ID", "Super User ID"], 1,
                    "SUID = Set User ID - executes file with owner's privileges.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("eh4", "Which Metasploit command shows available payloads?",
                    ["show exploits", "show payloads", "show auxiliary", "show options"], 1,
                    "show payloads lists all available payloads.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("eh5", "What is the purpose of LinPEAS?",
                    ["Linux privilege escalation automated script", "Network scanner", "Password cracker", "Web scanner"], 0,
                    "LinPEAS automates Linux privilege escalation enumeration.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("eh6", "What is lateral movement?",
                    ["Moving from one network to another", "Pivoting between compromised systems", "Physical movement", "Data exfiltration"], 1,
                    "Lateral movement is pivoting between systems after initial compromise.", DifficultyLevel.ADVANCED),
                QuizQuestion("eh7", "What information should a penetration test report include?",
                    ["Only successful exploits", "All findings with risk ratings and remediation", "Only executive summary", "Only screenshots"], 1,
                    "Comprehensive reports include all findings with risk and remediation.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("eh8", "What is the difference between black box and white box testing?",
                    ["No difference", "Black box has no prior knowledge; white box has full knowledge", "Black box is automated", "White box is illegal"], 1,
                    "Black box tests without prior knowledge; white box has full information.", DifficultyLevel.BEGINNER),
                QuizQuestion("eh9", "Which protocol is commonly used for network share enumeration?",
                    ["HTTP", "SMB", "FTP", "SSH"], 1,
                    "SMB (Server Message Block) is used for Windows file shares.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("eh10", "What is a reverse shell?",
                    ["Shell that runs backwards", "Target connects back to attacker", "Encrypted shell", "Local shell"], 1,
                    "Reverse shell has the target connect back to the attacker's listener.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("eh11", "What is the purpose of theHarvester tool?",
                    ["OSINT email and subdomain harvesting", "Password cracking", "Network scanning", "Malware analysis"], 0,
                    "theHarvester gathers emails, names, subdomains, and IPs from public sources.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("eh12", "What does CVSS stand for?",
                    ["Common Vulnerability Scoring System", "Computer Vulnerability Security Score", "Common Virus Scoring System", "Critical Vulnerability Severity Score"], 0,
                    "CVSS = Common Vulnerability Scoring System.", DifficultyLevel.BEGINNER),
            ],
        ),
    )

    # ========================================================================
    # COURSE 5: INCIDENT RESPONSE
    # ========================================================================
    mod5 = SecurityModule(
        id="ir_001",
        course_id="incident_response",
        title="Incident Response & Digital Forensics",
        description="Learn to detect, analyze, and respond to cybersecurity incidents effectively with structured response frameworks.",
        category=CourseCategory.DEFENSIVE,
        difficulty=DifficultyLevel.INTERMEDIATE,
        duration_hours=16.0,
        prerequisites=["Network Security Fundamentals"],
        order=5,
        lessons=[
            SecurityLesson(
                id="ir_l1", module_id="ir_001", title="Incident Response Frameworks",
                content="NIST SP 800-61 and SANS Incident Response Process. Preparation, detection, analysis, containment, eradication, recovery, and post-incident activity phases. Building an IR team, defining roles, and establishing communication protocols.",
                lesson_type=LessonType.TEXT, duration_min=50, order=1,
            ),
            SecurityLesson(
                id="ir_l2", module_id="ir_001", title="Detection & Analysis",
                content="SIEM implementation, log analysis, anomaly detection, and threat hunting. Indicator of Compromise (IOC) identification, timeline creation, and initial assessment procedures.",
                lesson_type=LessonType.INTERACTIVE, duration_min=60, order=2,
            ),
            SecurityLesson(
                id="ir_l3", module_id="ir_001", title="Containment Strategies",
                content="Short-term and long-term containment strategies. Network segmentation, isolation techniques, and evidence preservation. Balancing business continuity with security requirements.",
                lesson_type=LessonType.TEXT, duration_min=45, order=3,
            ),
            SecurityLesson(
                id="ir_l4", module_id="ir_001", title="Eradication & Recovery",
                content="Complete malware removal, vulnerability patching, system rebuilding, and secure restoration. Verification procedures and monitoring for persistence mechanisms.",
                lesson_type=LessonType.LAB, duration_min=55, order=4,
            ),
            SecurityLesson(
                id="ir_l5", module_id="ir_001", title="Digital Forensics Fundamentals",
                content="Forensic investigation principles: chain of custody, evidence integrity, and legal considerations. Disk imaging, file system analysis, and memory forensics.",
                lesson_type=LessonType.LAB, duration_min=65, order=5,
            ),
            SecurityLesson(
                id="ir_l6", module_id="ir_001", title="Memory Forensics",
                content="RAM analysis with Volatility and Rekall. Identifying malicious processes, network connections, and injected code. Memory artifact extraction and analysis.",
                lesson_type=LessonType.LAB, duration_min=70, order=6,
            ),
            SecurityLesson(
                id="ir_l7", module_id="ir_001", title="Log Analysis & Correlation",
                content="Windows Event Log, syslog, and application log analysis. Log correlation techniques, timeline analysis, and automated parsing with Splunk and ELK Stack.",
                lesson_type=LessonType.INTERACTIVE, duration_min=50, order=7,
            ),
            SecurityLesson(
                id="ir_l8", module_id="ir_001", title="Threat Hunting",
                content="Proactive threat hunting methodologies: hypothesis-driven hunting, IoC-based hunting, and behavioral analytics. MITRE ATT&CK framework mapping and detection engineering.",
                lesson_type=LessonType.INTERACTIVE, duration_min=55, order=8,
            ),
        ],
        labs=[
            SecurityLab(
                id="ir_lab1", module_id="ir_001",
                title="Incident Response Simulation",
                description="Respond to a simulated ransomware attack from detection to recovery.",
                environment="Virtualized enterprise network with Windows AD, Linux servers, and SIEM.",
                tasks=[
                    "Detect initial compromise through SIEM alerts",
                    "Analyze malware sample and identify IOCs",
                    "Create incident timeline",
                    "Isolate affected systems",
                    "Eradicate malware and close entry points",
                    "Recover systems from clean backups",
                    "Document lessons learned",
                ],
                hints=[
                    "Check for lateral movement via SMB/RDP",
                    "Analyze DNS queries for C2 beaconing",
                    "Look for scheduled tasks and registry run keys",
                ],
                solution="Structured IR process: detect -> analyze -> contain -> eradicate -> recover -> document",
                duration_min=120, points=200,
            ),
            SecurityLab(
                id="ir_lab2", module_id="ir_001",
                title="Memory Forensics Analysis",
                description="Analyze a memory dump to identify malware and attacker activities.",
                environment="Volatility 3, Rekall, Windows 10 memory dump, Kali Linux.",
                tasks=[
                    "Identify operating system and profile",
                    "List processes and identify suspicious ones",
                    "Check network connections and listening ports",
                    "Extract injected code and DLLs",
                    "Analyze registry hives for persistence",
                    "Reconstruct attack timeline",
                    "Extract and analyze malware samples",
                ],
                hints=[
                    "Look for processes with suspicious parent-child relationships",
                    "Check for hollowed processes",
                    "Analyze VAD tree for injected code",
                ],
                solution="Systematic memory analysis using Volatility plugins to identify malicious activity",
                duration_min=100, points=175,
            ),
            SecurityLab(
                id="ir_lab3", module_id="ir_001",
                title="Log Analysis Challenge",
                description="Analyze compromised system logs to reconstruct the attack timeline.",
                environment="Splunk instance with Windows and Linux logs from compromised environment.",
                tasks=[
                    "Identify initial access vector from logs",
                    "Track attacker lateral movement",
                    "Identify privilege escalation activities",
                    "Find data exfiltration evidence",
                    "Create comprehensive timeline",
                    "Generate IOC list for detection",
                ],
                hints=[
                    "Start with authentication logs",
                    "Look for unusual process execution patterns",
                    "Correlate network logs with endpoint logs",
                ],
                solution="Log correlation and timeline reconstruction using Splunk queries and manual analysis",
                duration_min=90, points=150,
            ),
        ],
        quiz=SecurityQuiz(
            id="ir_q1", module_id="ir_001", title="Incident Response Assessment",
            passing_score=75, time_limit_minutes=30,
            questions=[
                QuizQuestion("ir1", "What are the 6 phases of NIST incident response?",
                    ["Detect, Block, Remove, Recover, Learn, Report", "Preparation, Detection, Analysis, Containment, Eradication, Recovery", "Plan, Do, Check, Act", "Identify, Protect, Detect, Respond, Recover"], 1,
                    "NIST SP 800-61 defines these 6 phases.", DifficultyLevel.BEGINNER),
                QuizQuestion("ir2", "What is the primary goal of containment?",
                    ["Punish attackers", "Prevent further damage", "Delete all logs", "Disconnect everything"], 1,
                    "Containment aims to prevent further damage while preserving evidence.", DifficultyLevel.BEGINNER),
                QuizQuestion("ir3", "What is chain of custody?",
                    ["A type of malware", "Documentation of evidence handling", "Network protocol", "Encryption method"], 1,
                    "Chain of custody documents who handled evidence and when.", DifficultyLevel.BEGINNER),
                QuizQuestion("ir4", "Which tool is commonly used for memory forensics?",
                    ["Nmap", "Volatility", "Metasploit", "Wireshark"], 1,
                    "Volatility is the leading open-source memory forensics framework.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("ir5", "What is an Indicator of Compromise (IOC)?",
                    ["A type of firewall", "Evidence of potential intrusion", "A security policy", "An encryption key"], 1,
                    "IOCs are forensic artifacts indicating potential intrusion activity.", DifficultyLevel.BEGINNER),
                QuizQuestion("ir6", "What is threat hunting?",
                    ["Searching for malware signatures", "Proactively searching for threats", "Removing viruses", "Installing patches"], 1,
                    "Threat hunting is proactively searching for threats that evaded detection.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("ir7", "What is the MITRE ATT&CK framework?",
                    ["A programming language", "A knowledge base of adversary tactics", "A firewall", "An antivirus"], 1,
                    "MITRE ATT&CK is a globally-accessible knowledge base of adversary tactics.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("ir8", "What should be done first when discovering an active breach?",
                    ["Format all systems", "Isolate affected systems", "Ignore it", "Call the media"], 1,
                    "Isolation prevents further spread while preserving evidence.", DifficultyLevel.BEGINNER),
                QuizQuestion("ir9", "What is the purpose of a SIEM?",
                    ["Security Information and Event Management", "Software Installation and Execution Manager", "System Integrity Evaluation Module", "Secure Internet Email Manager"], 0,
                    "SIEM collects and analyzes security event data from across the environment.", DifficultyLevel.BEGINNER),
                QuizQuestion("ir10", "What is volatility analysis?",
                    ["Stock market analysis", "Memory forensics analysis", "Network traffic analysis", "Malware behavior analysis"], 1,
                    "Volatility analysis examines RAM contents for forensic artifacts.", DifficultyLevel.INTERMEDIATE),
            ],
        ),
    )

    # ========================================================================
    # COURSE 6: CLOUD SECURITY
    # ========================================================================
    mod6 = SecurityModule(
        id="cloudsec_001",
        course_id="cloud_security",
        title="Cloud Security (AWS, Azure, GCP)",
        description="Secure cloud infrastructure across major platforms: identity management, network security, data protection, and compliance.",
        category=CourseCategory.CLOUD,
        difficulty=DifficultyLevel.INTERMEDIATE,
        duration_hours=14.0,
        prerequisites=["Network Security Fundamentals"],
        order=6,
        lessons=[
            SecurityLesson(
                id="csl1", module_id="cloudsec_001", title="Cloud Security Fundamentals",
                content="Shared responsibility model, cloud deployment models (IaaS, PaaS, SaaS), and security implications. Cloud-native threats and attack vectors specific to cloud environments.",
                lesson_type=LessonType.TEXT, duration_min=45, order=1,
            ),
            SecurityLesson(
                id="csl2", module_id="cloudsec_001", title="Identity & Access Management",
                content="IAM policies, roles, and permissions across AWS IAM, Azure AD, and GCP IAM. Principle of least privilege, MFA implementation, and privileged access management.",
                lesson_type=LessonType.INTERACTIVE, duration_min=55, order=2,
            ),
            SecurityLesson(
                id="csl3", module_id="cloudsec_001", title="Cloud Network Security",
                content="VPC/VNet configuration, security groups, NACLs, WAF deployment, and DDoS protection. Cloud-native firewalls and zero-trust network architecture.",
                lesson_type=LessonType.LAB, duration_min=60, order=3,
            ),
            SecurityLesson(
                id="csl4", module_id="cloudsec_001", title="Data Protection & Encryption",
                content="Encryption at rest and in transit, key management services (KMS, AKV, CKM), data classification, and DLP strategies. Database encryption and secret management.",
                lesson_type=LessonType.INTERACTIVE, duration_min=50, order=4,
            ),
            SecurityLesson(
                id="csl5", module_id="cloudsec_001", title="Container & Kubernetes Security",
                content="Docker security, Kubernetes RBAC, pod security policies, network policies, and container scanning. Supply chain security and image signing.",
                lesson_type=LessonType.LAB, duration_min=65, order=5,
            ),
            SecurityLesson(
                id="csl6", module_id="cloudsec_001", title="Serverless Security",
                content="Securing AWS Lambda, Azure Functions, and Cloud Functions. Function-level permissions, environment variable security, and API gateway protection.",
                lesson_type=LessonType.TEXT, duration_min=40, order=6,
            ),
            SecurityLesson(
                id="csl7", module_id="cloudsec_001", title="Cloud Compliance & Governance",
                content="Compliance frameworks for cloud: SOC 2, PCI DSS, HIPAA, GDPR. Cloud security posture management (CSPM), cloud workload protection platforms (CWPP), and compliance automation.",
                lesson_type=LessonType.TEXT, duration_min=45, order=7,
            ),
            SecurityLesson(
                id="csl8", module_id="cloudsec_001", title="Cloud Forensics",
                content="Cloud-specific forensic challenges: volatile evidence, multi-tenancy, jurisdiction issues. AWS CloudTrail, Azure Monitor, and GCP Audit Logs analysis.",
                lesson_type=LessonType.LAB, duration_min=55, order=8,
            ),
        ],
        labs=[
            SecurityLab(
                id="cs_lab1", module_id="cloudsec_001",
                title="Secure AWS Infrastructure",
                description="Build a secure multi-tier AWS architecture with proper IAM, networking, and encryption.",
                environment="AWS Free Tier account, AWS CLI, Terraform.",
                tasks=[
                    "Create VPC with public and private subnets",
                    "Configure security groups with least privilege",
                    "Set up IAM roles and policies",
                    "Enable CloudTrail for audit logging",
                    "Configure S3 bucket encryption and policies",
                    "Set up AWS WAF for web application protection",
                    "Enable GuardDuty for threat detection",
                ],
                hints=[
                    "Use Terraform for infrastructure as code",
                    "Enable MFA for root account first",
                    "Use VPC Flow Logs for network monitoring",
                ],
                solution="Terraform configuration with security best practices for each AWS service",
                duration_min=120, points=200,
            ),
            SecurityLab(
                id="cs_lab2", module_id="cloudsec_001",
                title="Kubernetes Security Hardening",
                description="Secure a Kubernetes cluster with RBAC, network policies, and pod security.",
                environment="Minikube or EKS cluster, kubectl, helm.",
                tasks=[
                    "Configure RBAC with service accounts and roles",
                    "Implement network policies for pod isolation",
                    "Enable pod security standards",
                    "Set up admission controllers",
                    "Configure secrets management",
                    "Enable audit logging",
                    "Scan images for vulnerabilities",
                ],
                hints=[
                    "Start with restrictive pod security standards",
                    "Use network policies to enforce zero-trust",
                    "Regularly scan images with Trivy or Clair",
                ],
                solution="Comprehensive Kubernetes security configuration following CIS benchmarks",
                duration_min=100, points=175,
            ),
            SecurityLab(
                id="cs_lab3", module_id="cloudsec_001",
                title="Cloud Forensics Investigation",
                description="Investigate a compromised AWS account using CloudTrail and native tools.",
                environment="AWS account with CloudTrail, Athena, and compromised resources.",
                tasks=[
                    "Analyze CloudTrail logs for unauthorized API calls",
                    "Identify compromised IAM credentials",
                    "Track resource modifications",
                    "Identify data exfiltration attempts",
                    "Determine attack timeline",
                    "Implement remediation measures",
                ],
                hints=[
                    "Use Athena for CloudTrail log analysis",
                    "Check for unusual API call patterns",
                    "Look for IAM policy modifications",
                ],
                solution="CloudTrail analysis with Athena queries to reconstruct attack timeline",
                duration_min=90, points=150,
            ),
        ],
        quiz=SecurityQuiz(
            id="cs_q1", module_id="cloudsec_001", title="Cloud Security Assessment",
            passing_score=75, time_limit_minutes=30,
            questions=[
                QuizQuestion("cs1", "What is the shared responsibility model?",
                    ["Cloud provider handles all security", "Security responsibilities are split between provider and customer", "Customer handles all security", "Third party handles security"], 1,
                    "Security responsibilities are shared between cloud provider and customer.", DifficultyLevel.BEGINNER),
                QuizQuestion("cs2", "What does IAM stand for?",
                    ["Internet Access Method", "Identity and Access Management", "Integrated Account Manager", "Internal Audit Module"], 1,
                    "IAM = Identity and Access Management.", DifficultyLevel.BEGINNER),
                QuizQuestion("cs3", "Which AWS service provides threat detection?",
                    ["CloudWatch", "GuardDuty", "CloudFormation", "Route 53"], 1,
                    "GuardDuty is AWS's intelligent threat detection service.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("cs4", "What is the principle of least privilege?",
                    ["Give everyone admin access", "Grant minimum necessary permissions", "Deny all access", "Use single sign-on"], 1,
                    "Least privilege means granting only the minimum necessary permissions.", DifficultyLevel.BEGINNER),
                QuizQuestion("cs5", "What is a VPC?",
                    ["Virtual Private Cloud", "Virtual Public Cloud", "Very Private Connection", "Virtual Protocol Controller"], 0,
                    "VPC = Virtual Private Cloud - isolated network in the cloud.", DifficultyLevel.BEGINNER),
                QuizQuestion("cs6", "What is the purpose of Kubernetes RBAC?",
                    ["Resource monitoring", "Role-based access control for cluster resources", "Network routing", "Load balancing"], 1,
                    "RBAC controls who can access Kubernetes resources and what they can do.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("cs7", "What is CSPM?",
                    ["Cloud Security Posture Management", "Cloud Service Provider Management", "Customer Security Policy Module", "Centralized Security Protocol Manager"], 0,
                    "CSPM continuously monitors cloud infrastructure for security misconfigurations.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("cs8", "Which encryption protects data in transit?",
                    ["AES-256", "TLS/SSL", "RSA-4096", "SHA-256"], 1,
                    "TLS/SSL encrypts data during transmission over networks.", DifficultyLevel.BEGINNER),
                QuizQuestion("cs9", "What is container escape?",
                    ["A container exiting normally", "Breaking out of container isolation to host", "Moving containers between hosts", "Container networking"], 1,
                    "Container escape is a vulnerability allowing access to the host system.", DifficultyLevel.ADVANCED),
                QuizQuestion("cs10", "What is the purpose of CloudTrail?",
                    ["Performance monitoring", "Audit logging of AWS API calls", "Cost optimization", "Network routing"], 1,
                    "CloudTrail logs all AWS API calls for audit and compliance purposes.", DifficultyLevel.BEGINNER),
            ],
        ),
    )

    # ========================================================================
    # COURSE 7: MALWARE ANALYSIS
    # ========================================================================
    mod7 = SecurityModule(
        id="malware_001",
        course_id="malware_analysis",
        title="Malware Analysis & Reverse Engineering",
        description="Analyze malicious software to understand its behavior, identify IOCs, and develop detection methods.",
        category=CourseCategory.MALWARE,
        difficulty=DifficultyLevel.ADVANCED,
        duration_hours=18.0,
        prerequisites=["Programming fundamentals", "Operating system internals"],
        order=7,
        lessons=[
            SecurityLesson(
                id="ma_l1", module_id="malware_001", title="Malware Analysis Fundamentals",
                content="Types of malware: viruses, worms, trojans, ransomware, spyware, rootkits. Analysis methodologies: static, dynamic, and hybrid approaches. Setting up safe analysis environments.",
                lesson_type=LessonType.TEXT, duration_min=50, order=1,
            ),
            SecurityLesson(
                id="ma_l2", module_id="malware_001", title="Static Analysis Techniques",
                content="Analyzing malware without execution: PE structure analysis, string extraction, import table analysis, and entropy calculation. Tools: IDA Free, PEStudio, Detect It Easy.",
                lesson_type=LessonType.LAB, duration_min=60, order=2,
            ),
            SecurityLesson(
                id="ma_l3", module_id="malware_001", title="Dynamic Analysis",
                content="Executing malware in controlled environments: sandbox setup, behavior monitoring, API hooking, and network traffic analysis. Tools: Cuckoo Sandbox, Any.Run, Joe Sandbox.",
                lesson_type=LessonType.LAB, duration_min=65, order=3,
            ),
            SecurityLesson(
                id="ma_l4", module_id="malware_001", title="Reverse Engineering with IDA Pro",
                content="IDA Pro fundamentals: navigation, cross-references, function analysis, and decompilation. Understanding assembly code, recognizing algorithms, and reconstructing program logic.",
                lesson_type=LessonType.LAB, duration_min=70, order=4,
            ),
            SecurityLesson(
                id="ma_l5", module_id="malware_001", title="x86/x64 Assembly",
                content="Intel assembly language: registers, instructions, calling conventions, stack operations, and control flow. Essential assembly for malware analysis.",
                lesson_type=LessonType.INTERACTIVE, duration_min=60, order=5,
            ),
            SecurityLesson(
                id="ma_l6", module_id="malware_001", title="Anti-Analysis Techniques",
                content="Common anti-analysis techniques: packing, obfuscation, anti-debugging, anti-VM, and anti-sandbox. Identifying and bypassing these protections.",
                lesson_type=LessonType.LAB, duration_min=55, order=6,
            ),
            SecurityLesson(
                id="ma_l7", module_id="malware_001", title="Ransomware Analysis",
                content="Analyzing ransomware: encryption mechanisms, key management, file targeting, and network communication. Decryption possibilities and incident response.",
                lesson_type=LessonType.LAB, duration_min=65, order=7,
            ),
            SecurityLesson(
                id="ma_l8", module_id="malware_001", title="Shellcode Analysis",
                content="Shellcode extraction, encoding, and analysis. Position-independent code, egg hunters, and stagers. Tools for shellcode debugging and analysis.",
                lesson_type=LessonType.LAB, duration_min=60, order=8,
            ),
        ],
        labs=[
            SecurityLab(
                id="ma_lab1", module_id="malware_001",
                title="Static Malware Analysis",
                description="Perform comprehensive static analysis on real malware samples.",
                environment="REMnux virtual machine, FLARE VM, IDA Free, sample files.",
                tasks=[
                    "Identify file type and packing status",
                    "Extract and analyze strings",
                    "Analyze import table for suspicious APIs",
                    "Check file entropy for encrypted/packed sections",
                    "Identify potential C2 domains/IPs",
                    "Generate YARA rules for detection",
                    "Document findings and IOCs",
                ],
                hints=[
                    "Start with 'file' and 'peframe' for initial assessment",
                    "High entropy (>7.5) suggests packed/encrypted sections",
                    "Suspicious APIs: VirtualAlloc, CreateRemoteThread, InternetConnect",
                ],
                solution="Systematic static analysis workflow from initial triage to IOC extraction",
                duration_min=120, points=200,
            ),
            SecurityLab(
                id="ma_lab2", module_id="malware_001",
                title="Dynamic Malware Analysis",
                description="Execute and monitor malware behavior in a controlled sandbox environment.",
                environment="Cuckoo Sandbox, Windows 10 VM, INetSim for network simulation.",
                tasks=[
                    "Submit sample to Cuckoo Sandbox",
                    "Monitor file system changes",
                    "Capture network traffic and identify C2",
                    "Analyze API call sequences",
                    "Identify persistence mechanisms",
                    "Extract dropped files and memory dumps",
                    "Document complete behavior profile",
                ],
                hints=[
                    "Use INetSim to safely simulate internet services",
                    "Monitor registry changes for persistence",
                    "Check for process injection techniques",
                ],
                solution="Controlled dynamic analysis with comprehensive behavioral monitoring",
                duration_min=100, points=175,
            ),
            SecurityLab(
                id="ma_lab3", module_id="malware_001",
                title="Reverse Engineering Challenge",
                description="Reverse engineer a simple crackme to understand key validation logic.",
                environment="IDA Free, x64dbg, crackme samples, Windows VM.",
                tasks=[
                    "Identify key validation function",
                    "Trace input processing logic",
                    "Identify comparison algorithm",
                    "Extract key generation algorithm",
                    "Write key generator",
                    "Document reverse engineering process",
                ],
                hints=[
                    "Look for string comparison functions",
                    "Trace from input dialog to validation",
                    "Use cross-references on error messages",
                ],
                solution="Methodical reverse engineering from entry point to algorithm extraction",
                duration_min=150, points=250,
            ),
        ],
        quiz=SecurityQuiz(
            id="ma_q1", module_id="malware_001", title="Malware Analysis Assessment",
            passing_score=80, time_limit_minutes=35,
            questions=[
                QuizQuestion("ma1", "What is the difference between static and dynamic analysis?",
                    ["Static requires execution, dynamic does not", "Static does not require execution, dynamic does", "Both require execution", "Neither requires execution"], 1,
                    "Static analysis examines code without execution; dynamic observes runtime behavior.", DifficultyLevel.BEGINNER),
                QuizQuestion("ma2", "What is a packer?",
                    ["A compression tool", "Software that compresses/obfuscates executable code", "A file archiver", "A network tool"], 1,
                    "Packers compress/encrypt executables to evade detection and analysis.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("ma3", "What does high entropy in a PE section indicate?",
                    ["Normal code", "Packed/encrypted data", "Debug information", "Resource data"], 1,
                    "High entropy (>7.5) typically indicates packed or encrypted data.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("ma4", "What is the purpose of the .idata section?",
                    ["Store initialized data", "Store import table information", "Store code", "Store resources"], 1,
                    ".idata contains the import address table with imported function pointers.", DifficultyLevel.ADVANCED),
                QuizQuestion("ma5", "Which API call is commonly used for process injection?",
                    ["CreateFile", "CreateRemoteThread", "ReadFile", "WriteFile"], 1,
                    "CreateRemoteThread is commonly used for DLL injection.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("ma6", "What is a sandbox escape?",
                    ["A game", "Malware breaking out of analysis environment", "A security feature", "A type of encryption"], 1,
                    "Sandbox escape is when malware detects and breaks out of analysis environments.", DifficultyLevel.ADVANCED),
                QuizQuestion("ma7", "What is shellcode?",
                    ["Code that runs in a shell", "Small position-independent code for exploitation", "Python scripts", "Batch files"], 1,
                    "Shellcode is small position-independent code used as payload in exploits.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("ma8", "What is the purpose of API hooking in malware analysis?",
                    ["To improve performance", "To monitor API calls made by malware", "To encrypt data", "To compress files"], 1,
                    "API hooking intercepts and logs API calls to understand malware behavior.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("ma9", "What is a YARA rule?",
                    ["A Python library", "Pattern matching for malware identification", "A network protocol", "A hash function"], 1,
                    "YARA rules define patterns to identify and classify malware samples.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("ma10", "What is anti-debugging?",
                    ["A security feature", "Techniques to prevent debugging/analysis", "A type of malware", "A debugger tool"], 1,
                    "Anti-debugging techniques detect and thwart debugging attempts.", DifficultyLevel.ADVANCED),
            ],
        ),
    )

    # ========================================================================
    # COURSE 8: DIGITAL FORENSICS
    # ========================================================================
    mod8 = SecurityModule(
        id="forensics_001",
        course_id="digital_forensics",
        title="Digital Forensics Investigation",
        description="Comprehensive digital forensics techniques for investigating cyber incidents and gathering legal evidence.",
        category=CourseCategory.FORENSICS,
        difficulty=DifficultyLevel.INTERMEDIATE,
        duration_hours=15.0,
        prerequisites=["Operating system fundamentals"],
        order=8,
        lessons=[
            SecurityLesson(
                id="df_l1", module_id="forensics_001", title="Digital Forensics Principles",
                content="Core principles: evidence integrity, chain of custody, legal considerations, and admissibility standards. ACPO guidelines and digital evidence handling procedures.",
                lesson_type=LessonType.TEXT, duration_min=45, order=1,
            ),
            SecurityLesson(
                id="df_l2", module_id="forensics_001", title="Disk Imaging & Acquisition",
                content="Creating forensic disk images with dd, FTK Imager, and Guymager. Write blocking, hashing (MD5/SHA-256), and verification procedures.",
                lesson_type=LessonType.LAB, duration_min=55, order=2,
            ),
            SecurityLesson(
                id="df_l3", module_id="forensics_001", title="File System Analysis",
                content="NTFS, FAT, ext4 file system analysis. MFT examination, deleted file recovery, timeline analysis, and alternate data streams.",
                lesson_type=LessonType.LAB, duration_min=60, order=3,
            ),
            SecurityLesson(
                id="df_l4", module_id="forensics_001", title="Windows Forensics",
                content="Windows registry analysis, event log examination, prefetch analysis, LNK files, jump lists, and recycle bin forensics.",
                lesson_type=LessonType.LAB, duration_min=65, order=4,
            ),
            SecurityLesson(
                id="df_l5", module_id="forensics_001", title="Linux Forensics",
                content="Linux forensic artifacts: bash history, cron jobs, systemd journals, log files, and file system timestamps. Common attack traces on Linux systems.",
                lesson_type=LessonType.LAB, duration_min=55, order=5,
            ),
            SecurityLesson(
                id="df_l6", module_id="forensics_001", title="Network Forensics",
                content="Network traffic capture and analysis with Wireshark, tcpdump, and NetworkMiner. Protocol analysis, traffic reconstruction, and network timeline creation.",
                lesson_type=LessonType.LAB, duration_min=60, order=6,
            ),
            SecurityLesson(
                id="df_l7", module_id="forensics_001", title="Mobile Device Forensics",
                content="iOS and Android forensics: backup analysis, file system extraction, app data analysis, and cloud synchronization artifacts.",
                lesson_type=LessonType.INTERACTIVE, duration_min=50, order=7,
            ),
            SecurityLesson(
                id="df_l8", module_id="forensics_001", title="Report Writing & Expert Testimony",
                content="Professional forensic reporting: objective documentation, evidence presentation, and expert witness preparation. Legal standards and cross-examination preparation.",
                lesson_type=LessonType.TEXT, duration_min=40, order=8,
            ),
        ],
        labs=[
            SecurityLab(
                id="df_lab1", module_id="forensics_001",
                title="Disk Image Analysis",
                description="Analyze a forensic disk image to recover evidence of malicious activity.",
                environment="Autopsy, Sleuth Kit, forensic disk image, Kali Linux.",
                tasks=[
                    "Verify image integrity with hash comparison",
                    "Identify partition structure and file systems",
                    "Recover deleted files",
                    "Create file system timeline",
                    "Analyze internet artifacts",
                    "Search for keywords and patterns",
                    "Document all findings",
                ],
                hints=[
                    "Start with timeline analysis for overview",
                    "Check unallocated space for deleted files",
                    "Analyze browser history and cache",
                ],
                solution="Systematic disk analysis using Autopsy for comprehensive evidence recovery",
                duration_min=120, points=200,
            ),
            SecurityLab(
                id="df_lab2", module_id="forensics_001",
                title="Windows Registry Forensics",
                description="Analyze Windows registry hives to reconstruct user activity and system configuration.",
                environment="Registry Explorer, RECmd, Windows registry hives, parsed output.",
                tasks=[
                    "Parse SAM hive for user account information",
                    "Analyze SOFTWARE hive for installed programs",
                    "Examine NTUSER.DAT for user activity",
                    "Check SYSTEM hive for service configurations",
                    "Analyze USB device connections",
                    "Reconstruct network configuration",
                    "Document persistence mechanisms",
                ],
                hints=[
                    "USB devices recorded in SYSTEM\\CurrentControlSet\\Enum\\USBSTOR",
                    "UserAssist key shows executed programs",
                    "RecentDocs shows recently accessed documents",
                ],
                solution="Comprehensive registry analysis to reconstruct system and user activity",
                duration_min=100, points=175,
            ),
            SecurityLab(
                id="df_lab3", module_id="forensics_001",
                title="Network Forensics Investigation",
                description="Analyze network traffic captures to identify malicious activity.",
                environment="Wireshark, NetworkMiner, large PCAP file from compromised network.",
                tasks=[
                    "Identify all hosts and protocols",
                    "Detect port scanning activity",
                    "Identify malware C2 communications",
                    "Reconstruct transferred files",
                    "Analyze DNS queries for DGA patterns",
                    "Create network activity timeline",
                    "Extract all IOCs",
                ],
                hints=[
                    "Look for beaconing patterns in traffic",
                    "Check DNS queries for suspicious domains",
                    "Analyze HTTP User-Agent strings",
                ],
                solution="Network traffic analysis to identify threats and reconstruct attack timeline",
                duration_min=90, points=150,
            ),
        ],
        quiz=SecurityQuiz(
            id="df_q1", module_id="forensics_001", title="Digital Forensics Assessment",
            passing_score=75, time_limit_minutes=30,
            questions=[
                QuizQuestion("df1", "What is the first rule of digital forensics?",
                    ["Never turn off the computer", "Preserve evidence integrity", "Delete temporary files", "Install antivirus"], 1,
                    "Preserving evidence integrity is the fundamental rule.", DifficultyLevel.BEGINNER),
                QuizQuestion("df2", "What is a write blocker?",
                    ["A type of malware", "Hardware/software preventing writes to evidence", "A firewall", "An encryption tool"], 1,
                    "Write blockers prevent modification of original evidence.", DifficultyLevel.BEGINNER),
                QuizQuestion("df3", "What is the MFT in NTFS?",
                    ["Multi-File Transfer", "Master File Table", "Memory File Tracker", "Main Folder Tree"], 1,
                    "MFT = Master File Table - contains metadata for all files.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("df4", "Which hash is commonly used for evidence integrity?",
                    ["MD5 or SHA-256", "CRC32", "HMAC", "Base64"], 0,
                    "MD5 and SHA-256 are standard for evidence integrity verification.", DifficultyLevel.BEGINNER),
                QuizQuestion("df5", "What is chain of custody?",
                    ["A network protocol", "Documentation of evidence handling", "A type of encryption", "A security tool"], 1,
                    "Chain of custody documents all handling of evidence.", DifficultyLevel.BEGINNER),
                QuizQuestion("df6", "What tool is commonly used for disk imaging?",
                    ["Nmap", "FTK Imager", "Metasploit", "Wireshark"], 1,
                    "FTK Imager is a standard tool for forensic disk imaging.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("df7", "What is unallocated space?",
                    ["Free disk space that may contain deleted data", "RAM space", "Network bandwidth", "CPU cache"], 0,
                    "Unallocated space may contain recoverable deleted file data.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("df8", "What is timeline analysis?",
                    ["Social media analysis", "Chronological reconstruction of events", "Network mapping", "File sorting"], 1,
                    "Timeline analysis reconstructs events chronologically.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("df9", "What are Alternate Data Streams (ADS)?",
                    ["Hidden data attached to NTFS files", "Network streams", "Video files", "Backup files"], 0,
                    "ADS allows hidden data to be attached to files on NTFS.", DifficultyLevel.ADVANCED),
                QuizQuestion("df10", "What is the purpose of evidence hashing?",
                    ["Encrypt evidence", "Verify evidence integrity", "Compress evidence", "Hide evidence"], 1,
                    "Hashing verifies that evidence has not been modified.", DifficultyLevel.BEGINNER),
            ],
        ),
    )

    # Store courses 4-8
    _modules[mod4.id] = mod4
    _modules[mod5.id] = mod5
    _modules[mod6.id] = mod6
    _modules[mod7.id] = mod7
    _modules[mod8.id] = mod8

    # ========================================================================
    # COURSES 9-15 will be in part 3
    # ========================================================================
