    # COURSE 7: MALWARE ANALYSIS
    # ========================================================================
    mod7 = SecurityModule(
        id="malware_001",
        course_id="malware_analysis",
        title="Malware Analysis & Reverse Engineering",
        description="Analyze malicious software through static and dynamic techniques. Learn to dissect PE files, understand behavior, and identify indicators of compromise.",
        category=CourseCategory.MALWARE,
        difficulty=DifficultyLevel.ADVANCED,
        duration_hours=16.0,
        prerequisites=[["Assembly language basics"], ["Windows internals"], ["Cryptography fundamentals"]],
        order=7,
        lessons=[
            SecurityLesson(
                id="mal_l1", module_id="malware_001", title="Malware Taxonomy & Types",
                content="Classification of malware: viruses, worms, trojans, ransomware, spyware, adware, rootkits, bootkits, fileless malware, wipers. Infection vectors: phishing, drive-by downloads, supply chain, USB drops. Malware delivery mechanisms: droppers, downloaders, stagers. Modern malware families: Emotet, TrickBot, Ryuk, Cobalt Strike.",
                lesson_type=LessonType.TEXT, duration_min=50, order=1,
            ),
            SecurityLesson(
                id="mal_l2", module_id="malware_001", title="Static Analysis Techniques",
                content="Analyzing malware without execution: strings extraction, PE header analysis (DOS/NT headers, sections, imports/exports), resource analysis. Tools: PEStudio, CFF Explorer, Dependency Walker. File hashing (MD5, SHA-256, ssdeep), YARA rule writing, packing detection, entropy analysis for encrypted sections.",
                lesson_type=LessonType.INTERACTIVE, duration_min=65, order=2,
            ),
            SecurityLesson(
                id="mal_l3", module_id="malware_001", title="Dynamic Analysis & Sandboxing",
                content="Safe execution environments: isolated VMs, sandbox tools (Cuckoo, ANY.RUN, Joe Sandbox). Behavior monitoring: API hooking, registry changes, file system modifications, network activity. Memory analysis during execution. Evasive malware techniques: VM detection, timing checks, sandbox awareness.",
                lesson_type=LessonType.INTERACTIVE, duration_min=70, order=3,
            ),
            SecurityLesson(
                id="mal_l4", module_id="malware_001", title="YARA Rule Development",
                content="Writing effective YARA rules for malware detection and hunting. Rule structure: strings, conditions, modifiers. Advanced techniques: byte-level patterns, regular expressions, external variables, modules (PE, ELF, Math). Rule optimization and testing against large datasets.",
                lesson_type=LessonType.INTERACTIVE, duration_min=55, order=4,
            ),
            SecurityLesson(
                id="mal_l5", module_id="malware_001", title="Reverse Engineering Basics",
                content="Introduction to disassembly with IDA Pro Free and Ghidra. Understanding x86/x64 assembly, control flow, function calls, stack frames. Decompilation techniques, cross-references, and annotation. Identifying C2 communication, encryption routines, and obfuscation techniques.",
                lesson_type=LessonType.VIDEO, duration_min=60, order=5,
            ),
            SecurityLesson(
                id="mal_l6", module_id="malware_001", title="Ransomware Analysis",
                content="Deep dive into ransomware behavior: file enumeration, encryption routines, key management, ransom note delivery. Analysis of major ransomware families: WannaCry, NotPetya, Locky, REvil. Decryption possibilities, kill switches, and recovery strategies. Ransom negotiation considerations.",
                lesson_type=LessonType.INTERACTIVE, duration_min=65, order=6,
            ),
        ],
        labs=[
            SecurityLab(
                id="mal_lab1", module_id="malware_001",
                title="Static Analysis of Suspicious PE File",
                description="Perform comprehensive static analysis on a suspicious executable without running it.",
                environment="REMnux VM, PEStudio, CFF Explorer, strings, pestudio, ssdeep.",
                tasks=[
                    "Calculate MD5, SHA-256, and fuzzy hashes",
                    "Extract and analyze all printable strings",
                    "Parse PE headers and analyze section characteristics",
                    "Identify imported DLLs and suspicious API calls",
                    "Check for packing with UPX or custom packers",
                    "Analyze entropy of each section for encryption",
                    "Write a YARA rule for detection",
                ],
                hints=[
                    "High entropy (>7.5) sections may indicate packing/encryption",
                    "APIs like VirtualAlloc, CreateRemoteThread are suspicious",
                    "Check for unusual section names like .vm
p0, .upx",
                ],
                solution="strings -n 6 suspicious.exe | grep -i http; pestudio suspicious.exe; # Check imports: kernel32.dll: VirtualAlloc, WriteProcessMemory, CreateRemoteThread = code injection; # High entropy .text section indicates packing; YARA: rule SuspiciousPE { strings: $a=\"VirtualAlloc\" $b=\"CreateRemoteThread\" condition: uint16(0)==0x5A4D and all of them }",
                duration_min=75, points=150,
            ),
            SecurityLab(
                id="mal_lab2", module_id="malware_001",
                title="Dynamic Analysis in Controlled Environment",
                description="Execute and monitor malware behavior in a sandboxed environment.",
                environment="Isolated Windows 10 VM with INetSim, Wireshark, Procmon, Regshot, Cuckoo sandbox.",
                tasks=[
                    "Take system snapshot before execution",
                    "Execute malware and monitor process tree",
                    "Capture all network communications",
                    "Monitor registry modifications",
                    "Track file system changes",
                    "Identify persistence mechanisms",
                    "Extract C2 URLs and indicators",
                ],
                hints=[
                    "INetSim simulates internet services safely",
                    "Procmon filters: ProcessCreate, RegSetValue, WriteFile",
                    "Compare Regshot snapshots for registry changes",
                ],
                solution="Run in Cuckoo sandbox; Monitor with Procmon filter Operation is ProcessCreate or TCP Send; Wireshark filter dns or http; Identify: C2 at evil-domain.com, registry Run key for persistence, encrypted files in Documents folder = ransomware behavior",
                duration_min=90, points=175,
            ),
            SecurityLab(
                id="mal_lab3", module_id="malware_001",
                title="Ghidra Reverse Engineering",
                description="Use Ghidra to reverse engineer a simple crackme program.",
                environment="Ghidra 11.0, simple crackme binary, x86 reference materials.",
                tasks=[
                    "Import binary into Ghidra and run auto-analysis",
                    "Locate the main function in the decompiler",
                    "Identify user input function and comparison logic",
                    "Find the correct password string in the binary",
                    "Patch the binary to accept any password",
                    "Document the reverse engineering process",
                ],
                hints=[
                    "Look for strcmp or memcmp functions",
                    "Check string table for hardcoded values",
                    "Use cross-references to find where strings are used",
                ],
                solution="Import crackme into Ghidra; Find main at entry point; Decompile shows strcmp(user_input, 'SecretPass123'); Password is'SecretPass123'; Patch: change JNZ to JZ after comparison or NOP the jump",
                duration_min=90, points=175,
            ),
            SecurityLab(
                id="mal_lab4", module_id="malware_001",
                title="YARA Rule Development for Threat Hunting",
                description="Create YARA rules to detect a malware family based on identified indicators.",
                environment="REMnux, YARA, Python 3, sample malware files, VT API for verification.",
                tasks=[
                    "Extract unique strings from malware samples",
                    "Identify PE structure patterns common to the family",
                    "Write YARA rules with multiple string conditions",
                    "Test rules against known malware dataset",
                    "Optimize rules to minimize false positives",
                    "Document rule with metadata and description",
                ],
                hints=[
                    "Combine unique strings with PE structure checks",
                    "Use wide and ascii modifiers for Unicode strings",
                    "Test with yarac for compilation errors",
                ],
                solution="rule APT_Malware_Family { meta: author=\"Analyst\" description=\"Detects XYZ malware family\" strings: $mz={4D5A} $s1=\"C2_SERVER_URL\" wide ascii $s2=\"Mozilla/5.0 Custom\" $s3={68 ?? ?? ?? ?? E8 ?? ?? ?? ??} condition: $mz at 0 and 2 of ($s*) and filesize < 500KB }",
                duration_min=60, points=125,
            ),
        ],
        quiz=SecurityQuiz(
            id="mal_q1", module_id="malware_001", title="Malware Analysis Assessment",
            passing_score=75, time_limit_minutes=30,
            questions=[
                QuizQuestion("maq1", "What is the difference between static and dynamic analysis?",
                    ["Static is faster", "Static analyzes without execution; dynamic observes behavior during execution", "Dynamic is safer", "Stati
c requires a sandbox"], 1,
                    "Static analysis examines the file without running it; dynamic executes and monitors behavior.", DifficultyLevel.BEGINNER),
                QuizQuestion("maq2", "What does high entropy in a PE section typically indicate?",
                    ["The file is small", "Packed or encrypted data", "The file is safe", "High compression ratio"], 1,
                    "Entropy > 7.5 typically indicates packed, encrypted, or compressed data.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("maq3", "What is a YARA rule used for?",
                    ["Network scanning", "Pattern-based malware detection and classification", "Password cracking", "Website filtering"], 1,
                    "YARA rules use string patterns and conditions to identify and classify malware.", DifficultyLevel.BEGINNER),
                QuizQuestion("maq4", "What API call is commonly used for code injection?",
                    ["CreateFile", "CreateRemoteThread", "ReadFile", "DeleteFile"], 1,
                    "CreateRemoteThread injects and executes code in another process's address space.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("maq5", "What is a crypter in malware context?",
                    ["A password manager", "A tool that encrypts/obfuscates malware to evade detection", "A legitimate encryption tool", "A network protocol"], 1,
                    "CryPters encrypt/obfuscate malware payloads to evade signature-based detection.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("maq6", "What is the purpose of API hooking in dynamic analysis?",
                    ["Speed up the application", "Intercept and monitor API calls to understand behavior", "Bypass authentication", "Encrypt communications"], 1,
                    "API hooking intercepts function calls to monitor what the malware is doing.", DifficultyLevel.ADVANCED),
                QuizQuestion("maq7", "Which registry key is commonly used for persistence?",
                    ["HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\Run", "HKEY_CLASSES_ROOT\\.txt", "HKEY_USERS\\.Default", "HKEY_CURRENT_USER\\Environment"], 0,
                    "The Run key executes programs on startup and is commonly abused for persistence.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("maq8", "What is a fileless malware technique?",
                    ["Malware that only targets text files", "Malware that operates in memory without writing to disk", "Malware that deletes files", "Malware that targets file servers"], 1,
                    "Fileless malware operates in RAM using legitimate system tools, leaving minimal disk artifacts.", DifficultyLevel.ADVANCED),
                QuizQuestion("maq9", "What is UPX?",
                    ["An antivirus engine", "A packer that compresses executables", "A network protocol", "A file system"], 1,
                    "UPX (Ultimate Packer for eXecutables) is a common executable packer used legitimately and by malware.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("maq10", "What is the import address table (IAT) used for?",
                    ["Storing file icons", "Listing external DLL functions the executable uses", "Storing user passwords", "Managing network connections"], 1,
                    "IAT contains pointers to functions imported from external DLLs, revealing malware capabilities.", DifficultyLevel.ADVANCED),
                QuizQuestion("maq11", "What does ssdeep compute?",
                    ["SHA-256 hash", "Fuzzy hash for similarity matching", "File size", "Encryption key"], 1,
                    "ssdeep computes context-triggered piecewise hashes for similarity comparison between files.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("maq12", "What is a C2 (Command and Control) server?",
                    ["A backup server", "Server used by attackers to control compromised systems", "A content delivery server", "A certificate authority"], 1,
                    "C2 servers receive connections from compromised systems and issue commands to malware.", DifficultyLevel.BEGINNER),
                QuizQuestion("maq13", "Which tool is free and open-source for reverse engineering?",
                    ["IDA Pro", "Ghidra", "Binary Ninja", "Hopper"], 1,
                    "Ghidra is NSA's free, open-source reverse engineering framework with decompiler support.", DifficultyLevel.BEGINNER),
                QuizQuestion("maq14", "What is a ransomware kill switch?",
                    ["A hardware button", "A domain or mechanism that stops ransomware from executing", "An antivirus feature", "A network firewall"], 1,
                    "Kill switches like the WannaCry sinkhole domain can prevent ransomware from activating.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("maq15", "What technique do malware authors use to detect sandboxes?",
                    ["Netwo
rk speed tests", "VM detection: checking registry keys, MAC addresses, processes", "File size checks", "User agent checks"], 1,
                    "Malware checks for VM artifacts (e.g., VMWare tools, specific MAC prefixes) to evade sandboxes.", DifficultyLevel.ADVANCED),
            ],
        ),
    )

    # ========================================================================
    # COURSE 8: DIGITAL FORENSICS
    # ========================================================================
    mod8 = SecurityModule(
        id="df_001",
        course_id="digital_forensics",
        title="Digital Forensics & Investigation",
        description="Master evidence collection, preservation, and analysis across disk, memory, network, and mobile platforms following legal standards.",
        category=CourseCategory.FORENSICS,
        difficulty=DifficultyLevel.ADVANCED,
        duration_hours=15.0,
        prerequisites=[["File systems (NTFS, ext4)"], ["Operating system internals"]],
      order=8,
        lessons=[
            SecurityLesson(
                id="df_l1", module_id="df_001", title="Forensic Principles & Legal Framework",
                content="Digital forensics methodology: identification, preservation, collection, examination, analysis, reporting. Legal considerations: chain of custody, admissibility (Daubert standard), search warrants, privacy laws. Ethics in forensics: objectivity, documentation, expert testimony preparation. International frameworks and cross-border challenges.",
                lesson_type=LessonType.TEXT, duration_min=50, order=1,
            ),
            SecurityLesson(
                id="df_l2", module_id="df_001", title="Evidence Collection & Imaging",
                content="Forensic imaging techniques: bit-for-bit copying with dd, dc3dd, FTK Imager, Guymager. Write-blocking hardware and software. Hash verification (MD5, SHA-256) for integrity. Live vs dead system acquisition. Order of volatility: registers, cache, RAM, disk, remote storage. Documentation standards.",
                lesson_type=LessonType.INTERACTIVE, duration_min=60, order=2,
            ),
            SecurityLesson(
                id="df_l3", module_id="df_001", title="Disk Forensics with Autopsy",
                content="Using Autopsy and The Sleuth Kit for disk analysis: file system parsing (NTFS, FAT, ext, APFS), deleted file recovery, keyword searching, timeline generation. Hash databases (NSRL), EXIF data extraction, email parsing. Correlation of artifacts across the file system.",
                lesson_type=LessonType.INTERACTIVE, duration_min=65, order=3,
            ),
            SecurityLesson(
                id="df_l4", module_id="df_001", title="File Carving & Recovery",
                content="File carving techniques: header/footer signatures, structure-based carving, content-based carving. Tools: scalpel, foremost, PhotoRec, bulk_extractor. Carving from unallocated space, slack space, and swap files. Challenges: fragmentation, overwritten data, encrypted volumes.",
                lesson_type=LessonType.INTERACTIVE, duration_min=55, order=4,
            ),
            SecurityLesson(
                id="df_l5", module_id="df_001", title="Windows Registry Analysis",
                content="Registry structure: hives, keys, values. Critical forensic artifacts: UserAssist, ShimCache, AmCache, RecentDocs, TypedURLs, USB device history, network profiles. Tools: RegRipper, Registry Explorer. Timeline reconstruction from registry timestamps.",
                lesson_type=LessonType.VIDEO, duration_min=50, order=5,
            ),
            SecurityLesson(
                id="df_l6", module_id="df_001", title="Memory Forensics with Volatility",
                content="RAM acquisition and analysis with Volatility 3. Identifying running processes, network connections, loaded DLLs, open handles. Extracting credentials (mimikatz-style), detecting rootkits, analyzing malware in memory. Profile selection and plugin development.",
                lesson_type=LessonType.INTERACTIVE, duration_min=70, order=6,
            ),
            SecurityLesson(
                id="df_l7", module_id="df_001", title="Network Forensics",
                content="Analyzing network captures for forensic purposes: extracting files from PCAP, reconstructing sessions, identifying C2 traffic, detecting data exfiltration. Log correlation: firewall, proxy, DNS, DHCP. Tools: Wireshark, NetworkMiner, Zeek, Splunk for network analysis.",
                lesson_type=LessonType.INTERACTIVE, duration_min=60, order=7,
            ),
        ],
        labs=[
            SecurityLab(
                id="df_lab1", module_id="df_001",
                title="Forensic Disk Imaging and Verification",
                description="Create a forensic image of a suspect drive with full chain of custody documentation.",
                environment="SIFT Workstation, FTK Imager, dd, dc3dd, write blocker, USB drive.",
       tasks=[
                    "Document initial drive information (serial, capacity, model)",
                    "Connect drive through hardware write blocker",
                    "Create bit-for-bit image using dc3dd with hashing",
                    "Verify image integrity with MD5 and SHA-256 hashes",
                    "Create working copy and preserve original image",
                    "Document complete chain of custody form",
                    "Generate image metadata report",
                ],
                hints=[
                    "dc3dd if=/dev/sdb of=image.dd hash=md5,sha256 hashlog=hash.log",
                    "Always verify hash of image matches source before analysis",
                    "Use hardware write blockers to prevent evidence modification",
                ],
                solution="dc3dd if=/dev/sdb of=evidence.dd hash=md5 hashlog=md5.log hash=sha256 hashlog=sha256.log log=operation.log; md5sum evidence.dd; # Verify against source hash; # Chain of custody: document who, when, where, why for each handling",
                duration_min=60, points=125,
            ),
            SecurityLab(
                id="df_lab2", module_id="df_001",
                title="Memory Forensics Investigation",
                description="Analyze a memory dump to identify malware and extract forensic artifacts.",
                environment="SIFT Workstation, Volatility 3, Windows memory dump (.mem), YARA rules.",
                tasks=[
                    "Identify the correct Volatility profile for the memory dump",
                    "List all processes and identify suspicious ones",
                    "Extract network connections and identify C2 IPs",
                    "Dump suspicious process memory for further analysis",
                    "Extract cached credentials and password hashes",
                    "Identify injected code and hooking",
                    "Generate a comprehensive timeline of activity",
                ],
                hints=[
                    "vol.py -f dump.mem windows.pslist for process list",
                    "vol.py -f dump.mem windows.netscan for network connections",
                    "vol.py -f dump.mem windows.malfind for injected code",
                ],
                solution="vol.py -f memory.dmp windows.info; vol.py -f memory.dmp windows.pslist --pid [suspicious]; vol.py -f memory.dmp windows.netscan | grep ESTABLISHED; vol.py -f memory.dmp windows.malfind; vol.py -f memory.dmp windows.hashdump; Identify: svchost.exe with wrong parent, C2 at 185.x.x.x, LSASS injection detected",
                duration_min=90, points=175,
            ),
            SecurityLab(
                id="df_lab3", module_id="df_001",
                title="Timeline Analysis with Autopsy",
                description="Reconstruct a comprehensive timeline of user activity from a forensic image.",
                environment="Autopsy 4.21, sample forensic image (E01), timeline analysis tools.",
                tasks=[
                    "Import forensic image into Autopsy case",
                    "Run ingest modules: File Type, Hash Lookup, Keyword Search",
                    "Generate timeline from MAC times and registry",
                    "Identify file deletions and downloads",
                    "Correlate USB device connections with file activity",
                    "Reconstruct user browsing history",
                    "Export timeline report for case documentation",
                ],
                hints=[
                    "Ingest modules run automatically on image import",
                    "Timeline view shows file system events chronologically",
                    "Registry analysis reveals USB insertion times",
                ],
                solution="Create Autopsy case; Add data source (E01); Run ingest modules; Timeline: 2024-01-15 14:30 USB inserted; 14:35 files copied to E:; 15:00 files deleted from Desktop; 15:30 browser history cleared; Registry: USB serial found in SYSTEM\\ControlSet001\\Enum\\USBSTOR",
                duration_min=75, points=150,
            ),
            SecurityLab(
                id="df_lab4", module_id="df_001",
                title="Network Forensics: PCAP Investigation",
                description="Analyze a PCAP file to reconstruct an attack and identify compromised systems.",
                environment="Wireshark, NetworkMiner, Zeek, malicious.pcap sample.",
                tasks=[
                    "Identify initial compromise vector from PCAP",
                    "Track C2 communication patterns",
                    "Extract files transferred over the network",
                    "Identify data exfiltration attempts",
                    "Reconstruct the attack timeline",
                    "Identify all compromised internal hosts",
                ],
                hints=[
                    "Start with Statistics -> Conversations for overview",
            "Filter on dns queries for initial beaconing",
                    "Use Export Objects to extract transferred files",
                ],
                solution="Initial access: HTTP request to malicious site (drive-by download); C2: DNS beaconing to bad-domain.com every 300s; Exfil: HTTP POST to pastebin-like service with base64 data; Extracted: suspicious.exe, config.dat; Compromised: 192.168.1.105 (initial), lateral to 192.168.1.110 via SMB",
                duration_min=75, points=150,
            ),
        ],
        quiz=SecurityQuiz(
            id="df_q1", module_id="df_001", title="Digital Forensics Assessment",
            passing_score=75, time_limit_minutes=30,
            questions=[
                QuizQuestion("dfq1", "What is the most important principle in digital forensics?",
                    ["Speed", "Evidence integrity preservation", "Cost efficiency", "Using the latest tools"], 1,
                    "Maintaining evidence integrity through proper handling and documentation is paramount.", DifficultyLevel.BEGINNER),
                QuizQuestion("dfq2", "What is the order of volatility?",
                    ["CPU registers, cache, RAM, disk, archival", "Disk, RAM, cache, registers", "Archival, disk, RAM, cache", "RAM, disk, cache, registers"], 0,
                    "Order of volatility: registers/cache -> RAM -> disk -> remote storage. Collect most volatile first.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("dfq3", "What is the purpose of a write blocker?",
                    ["Prevent unauthorized access", "Prevent modification of evidence", "Speed up imaging", "Encrypt data"], 1,
                    "Write blockers prevent any writes to the original evidence media during acquisition.", DifficultyLevel.BEGINNER),
                QuizQuestion("dfq4", "What does Volatility framework analyze?",
                    ["Disk images", "Memory dumps", "Network packets", "Registry hives"], 1,
                    "Volatility is the leading open-source framework for memory forensics analysis.", DifficultyLevel.BEGINNER),
                QuizQuestion("dfq5", "What is file carving?",
                    ["Cutting physical drives", "Recovering files by their headers/footers without file system metadata", "Encrypting files", "Compressing files"], 1,
                    "File carving recovers files from raw data by identifying file signatures when file system metadata is unavailable.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("dfq6", "Which Windows registry hive contains user-specific settings?",
                    ["SYSTEM", "SOFTWARE", "NTUSER.DAT", "SAM"], 2,
                    "NTUSER.DAT contains HKEY_CURRENT_USER settings specific to each user profile.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("dfq7", "What is slack space?",
                    ["Free disk space", "Unused space at end of file clusters that may contain remnants", "RAM cache", "Swap space"], 1,
                    "File slack is the unused portion of the last cluster allocated to a file, which may contain previous data.", DifficultyLevel.ADVANCED),
                QuizQuestion("dfq8", "What is the chain of custody?",
                    ["A network diagram", "Documentation of evidence handling from collection to court", "An encryption key", "A backup procedure"], 1,
                    "Chain of custody documents every person who handled evidence, when, and why.", DifficultyLevel.BEGINNER),
                QuizQuestion("dfq9", "Which tool is commonly used for forensic disk imaging?",
                    ["Photoshop", "FTK Imager", "Microsoft Word", "Chrome"], 1,
                    "FTK Imager is a widely used free tool for creating forensic disk images.", DifficultyLevel.BEGINNER),
                QuizQuestion("dfq10", "What is the Daubert standard?",
                    ["A networking protocol", "Criteria for admissibility of expert scientific testimony in US courts", "An encryption algorithm", "A file format"], 1,
                    "Daubert standard determines whether expert testimony is admissible in US federal courts.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("dfq11", "What does MFT stand for in NTFS?",
                    ["Master File Table", "Memory Fault Tolerance", "Managed File Transfer", "Multi-Function Table"], 0,
                    "Master File Table (MFT) is the core metadata structure in NTFS containing file records.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("dfq12", "What is a forensic hash used for?",
                    ["Encrypt evidence", "Verify evidence integrity and identify known files", "Compress images", "Generate passwords"], 1,
                    "Cryptographic hashes verify evidence hasn't changed and identify known good/bad files via NSRL.", DifficultyLevel.BEGINNER),
                QuizQuestion("dfq13", "In memory forensics, what does malfind detect?",
                    ["Malic
ious network traffic", "Injected code and hooked DLLs", "Bad hard drives", "Virus definitions"], 1,
                    "malfind detects injected code by identifying memory regions with execute permissions and unusual characteristics.", DifficultyLevel.ADVANCED),
                QuizQuestion("dfq14", "What is the purpose of Zeek (formerly Bro) in network forensics?",
                    ["Packet capture only", "High-level network traffic analysis and event generation", "Disk imaging", "Registry analysis"], 1,
                    "Zeek extracts high-level events and metadata from network traffic beyond raw packet capture.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("dfq15", "What is LSB steganography?",
                    ["A file system", "Hiding data in the least significant bits of image pixels", "A network protocol", "A compression method"], 1,
                    "LSB steganography hides data by modifying the least significant bits of pixel values in images.", DifficultyLevel.ADVANCED),
            ],
        ),
    )


    # ========================================================================
    # COURSE 9: COMPLIANCE & GOVERNANCE
    # ========================================================================
    mod9 = SecurityModule(
        id="comp_001",
        course_id="compliance_governance",
        title="Security Compliance & Governance",
        description="Navigate the complex landscape of security compliance frameworks, risk management, and governance programs.",
        category=CourseCategory.COMPLIANCE,
        difficulty=DifficultyLevel.INTERMEDIATE,
        duration_hours=11.0,
        prerequisites=[],
        order=9,
        lessons=[
            SecurityLesson(
                id="comp_l1", module_id="comp_001", title="Security Governance Fundamentals",
                content="Information security governance: aligning security with business objectives. Governance frameworks: COBIT, ISO 27014, NIST CSF. Roles and responsibilities: CISO, security steering committee, data owners. Policy hierarchy: policies, standards, procedures, guidelines. Measuring security program effectiveness through KPIs and KRIs.",
                lesson_type=LessonType.TEXT, duration_min=45, order=1,
            ),
            SecurityLesson(
                id="comp_l2", module_id="comp_001", title="Risk Management Framework",
                content="Risk management lifecycle: identify, assess, treat, monitor. Risk assessment methodologies: qualitative (matrices), quantitative (ALE, SLE, ARO). Risk treatment options: avoid, mitigate, transfer, accept. NIST RMF (SP 800-37): prepare, categorize, select, implement, assess, authorize, monitor. Risk registers and heat maps.",
                lesson_type=LessonType.TEXT, duration_min=50, order=2,
            ),
            SecurityLesson(
                id="comp_l3", module_id="comp_001", title="ISO 27001/27002",
                content="ISO 27001 ISMS requirements: context, leadership, planning, support, operation, evaluation, improvement. Annex A controls: 114 controls across 4 themes. ISO 27002 implementation guidance. Certification process: gap analysis, risk assessment, SoA, internal audit, stage 1/2 external audit, surveillance. ISMS documentation requirements.",
                lesson_type=LessonType.TEXT, duration_min=55, order=3,
            ),
            SecurityLesson(
                id="comp_l4", module_id="comp_001", title="NIST Cybersecurity Framework",
                content="CSF 2.0 Core Functions: GOVERN, IDENTIFY, PROTECT, DETECT, RESPOND, RECOVER. Categories and subcategories with implementation examples. Tiers: Partial, Risk Informed, Repeatable, Adaptive. Profile creation: current vs target. Integration with NIST SP 800-53 controls. CSF 2.0 changes: added Govern function, supply chain risk.",
                lesson_type=LessonType.TEXT, duration_min=50, order=4,
            ),
            SecurityLesson(
                id="comp_l5", module_id="comp_001", title="PCI DSS 4.0",
                content="Payment Card Industry Data Security Standard v4.0: 12 requirements across 6 goals. Network segmentation, encryption, access controls, vulnerability management, monitoring, testing. SAQ types, ROC documentation, QSA assessments. New in 4.0: customized approach, targeted risk analysis, enhanced authentication requirements.",
                lesson_type=LessonType.TEXT, duration_min=45, order=5,
            ),
            SecurityLesson(
                id="comp_l6", module_id="comp_001", title="HIPAA & Healthcare Security",
                content="Health Insurance Portability and Accountability Act: Privacy Rule, Security Rule, Breach Notification Rule. Administrative, physical, technical safeguards. ePHI protection, access controls, audit controls, integrity controls. Risk analysis requirements. Business Associate Agreements (BAAs). OCR audit protocol. Penalties and enforcement.",
                lesson_type=LessonT
ype.TEXT, duration_min=40, order=6,
            ),
            SecurityLesson(
                id="comp_l7", module_id="comp_001", title="GDPR & Data Privacy",
                content="General Data Protection Regulation: principles, rights, obligations. Lawful basis for processing: consent, contract, legal obligation, vital interests, public task, legitimate interests. Data subject rights: access, rectification, erasure, portability, restriction, objection. DPO requirements, DPIA, cross-border transfers. Fines: up to 4% global turnover or €20M.",
                lesson_type=LessonType.TEXT, duration_min=55, order=7,
            ),
            SecurityLesson(
                id="comp_l8", module_id="comp_001", title="SOX, SOC 2 & IT Auditing",
                content="Sarbanes-Oxley Act: IT controls for financial reporting. SOC 2 Trust Services Criteria: security, availability, confidentiality, processing integrity, privacy. SOC 2 Type 1 vs Type 2. IT audit process: planning, fieldwork, reporting, follow-up. Continuous auditing and monitoring. Audit evidence: design vs operating effectiveness.",
                lesson_type=LessonType.TEXT, duration_min=45, order=8,
            ),
        ],
        labs=[
            SecurityLab(
                id="comp_lab1", module_id="comp_001",
                title="Risk Assessment Workshop",
                description="Conduct a comprehensive risk assessment for a fictional organization.",
                environment="Risk assessment templates, NIST RMF toolkit, spreadsheet software.",
                tasks=[
                    "Identify organizational assets and their values",
                    "Identify threats and vulnerabilities",
                    "Assess likelihood and impact for each risk",
                    "Calculate risk scores and create risk heat map",
                    "Prioritize risks and select treatment strategies",
                    "Create risk register with owners and timelines",
                    "Present findings to mock steering committee",
                ],
                hints=[
                    "Use qualitative scales: likelihood 1-5, impact 1-5",
                    "Consider likelihood × impact for risk score",
                    "Document risk appetite statement",
                ],
                solution="Asset inventory with values; Threat catalog (internal, external, environmental); Risk register with likelihood/impact scores; Heat map with high-priority quadrant; Treatment plan: mitigate critical, transfer acceptable, accept low; Risk owner assigned for each",
                duration_min=75, points=125,
            ),
            SecurityLab(
                id="comp_lab2", module_id="comp_001",
                title="ISO 27001 Gap Analysis",
                description="Perform a gap analysis against ISO 27001 Annex A controls for a sample organization.",
                environment="ISO 27001:2022 checklist, organizational documentation, spreadsheet.",
                tasks=[
                    "Review all 93 Annex A controls (2022 version)",
                    "Assess implementation status for each control",
                    "Document evidence of implementation where present",
                    "Identify gaps and missing controls",
                    "Create remediation plan with priorities",
                    "Estimate timeline and resources for closure",
                    "Generate gap analysis report",
                ],
                hints=[
                    "Group controls by theme: organizational, people, physical, technological",
                    "Score: Fully Met, Partially Met, Not Met, Not Applicable",
                    "Prioritize gaps by risk and certification requirements",
                ],
                solution="Review 93 controls across 4 themes; Score: 45 Fully Met, 28 Partially Met, 15 Not Met, 5 N/A; Critical gaps: A.5.7 Threat intelligence, A.5.18 Access rights, A.8.1 User endpoint devices; Remediation: 6-month plan with quarterly milestones",
                duration_min=90, points=175,
            ),
            SecurityLab(
                id="comp_lab3", module_id="comp_001",
                title="GDPR Data Mapping Exercise",
                description="Create a comprehensive data mapping and processing register for GDPR compliance.",
                environment="GDPR templates, data flow diagram tools, organizational data inventory.",
                tasks=[
                    "Identify all personal data processing activities",
                    "Map data flows: collection, use, storage, transfer, deletion",
                    "Document lawful basis for each processing activity",
                    "Identify data retention periods",
                    "Map cross-border data transfers",
                    "Assess need for DPIA",
                    "Create Records of Processing Activities (ROPA)",
                ],
                hints=[
        "Interview department heads for processing activities",
                    "Use Article 30 requirements for ROPA format",
                    "Flag high-risk processing requiring DPIA",
                ],
                solution="Identify 45 processing activities across HR, Marketing, Finance, IT; Lawful basis: 20 legitimate interest, 15 contract, 8 consent, 2 legal obligation; 3 high-risk activities flagged for DPIA; Cross-border transfers: US ( adequacy decision + SCCs); Retention schedule documented; ROPA completed",
                duration_min=60, points=125,
            ),
        ],
        quiz=SecurityQuiz(
            id="comp_q1", module_id="comp_001", title="Compliance & Governance Assessment",
            passing_score=70, time_limit_minutes=25,
            questions=[
                QuizQuestion("compq1", "What is the purpose of an ISMS?",
                    ["Network monitoring", "Systematic management of sensitive information", "Firewall configuration", "Penetration testing"], 1,
                    "ISMS (Information Security Management System) systematically manages sensitive company information.", DifficultyLevel.BEGINNER),
                QuizQuestion("compq2", "What does ALE calculate?",
                    ["Asset value", "Single Loss Expectancy × Annualized Rate of Occurrence", "Risk tolerance", "Control effectiveness"], 1,
                    "ALE (Annualized Loss Expectancy) = SLE × ARO, quantifying expected annual loss from a risk.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("compq3", "How many controls are in ISO 27001:2022 Annex A?",
                    ["114", "93", "68", "156"], 1,
                    "ISO 27001:2022 consolidated Annex A to 93 controls organized into 4 themes.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("compq4", "What are the NIST CSF 2.0 functions?",
                    ["GOVERN, IDENTIFY, PROTECT, DETECT, RESPOND, RECOVER", "PLAN, DO, CHECK, ACT", "PREVENT, DETECT, CORRECT", "STRATEGY, TACTICS, OPERATIONS"], 0,
                    "CSF 2.0 has 6 functions: GOVERN, IDENTIFY, PROTECT, DETECT, RESPOND, RECOVER.", DifficultyLevel.BEGINNER),
                QuizQuestion("compq5", "What is the maximum GDPR fine?",
                    ["€1 million", "€10 million or 2% global turnover", "€20 million or 4% global turnover", "€50 million"], 2,
                    "GDPR Article 83 sets maximum fines at €20M or 4% of global annual turnover (whichever is higher).", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("compq6", "What is a DPIA?",
                    ["Data Processing Impact Assessment", "Digital Privacy Information Act", "Data Protection Insurance Agreement", "Dynamic Processing Interface Architecture"], 0,
                    "DPIA (Data Protection Impact Assessment) assesses privacy risks of high-risk processing activities.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("compq7", "Which SOC 2 trust principle focuses on system availability?",
                    ["Security", "Availability", "Confidentiality", "Processing Integrity"], 1,
                    "Availability principle addresses whether systems are available for operation and use.", DifficultyLevel.BEGINNER),
                QuizQuestion("compq8", "What is the chain of custody in forensics?",
                    ["An encryption standard", "Documentation of evidence handling", "A network topology", "A backup strategy"], 1,
                    "Chain of custody documents all handling of evidence from collection to presentation in court.", DifficultyLevel.BEGINNER),
                QuizQuestion("compq9", "What does PCI DSS protect?",
                    ["All company data", "Cardholder data and sensitive authentication data", "Employee records", "Intellectual property"], 1,
                    "PCI DSS specifically protects cardholder data (CHD) and sensitive authentication data (SAD).", DifficultyLevel.BEGINNER),
                QuizQuestion("compq10", "What is the first step in NIST RMF?",
                    ["Implement controls", "Prepare", "Assess", "Authorize"], 1,
                    "NIST RMF Step 0 is Prepare, establishing organizational context and priorities.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("compq11", "What is a Business Associate Agreement (BAA)?",
                    ["A sales contract", "HIPAA-required contract for third-party PHI handlers", "A partnership agreement", "An employment contract"], 1,
                    "BAA is a HIPAA-required contract ensuring business associates protect PHI appropriately.", DifficultyLevel.INTERMEDIATE),
                QuizQuestion("compq12", "What is the difference between policies and procedures?",
                    ["They are the same", "Policies state what must be done; procedures describe how to do it", "Policies are technical; procedures are managerial", "Policies are optional; procedures are mandatory"], 1,
                    "Policies set 
# ___END_OF_FILE___